import type {
  Account,
  Deal,
  EmailTemplate,
  NotificationItem,
  Task,
} from "./types"

export const accounts: Account[] = [
  {
    id: "acc_1",
    name: "Fever",
    domain: "feverup.com",
    industry: "Entertainment & Events",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "San Francisco, CA",
    logoColor: "#E5006D",
    tier: "Enterprise",
    healthScore: 88,
    openDeals: 2,
    pipeline: 145000,
    contacts: 6,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T14:20:00Z",
    about:
      "Scaling their outbound motion with a new SDR team. Strong champion in the VP of Sales.",
    signals: ["Hiring SDRs", "Visited pricing page", "Series C funding"],
    keyExecutives: [
      { name: "Sarah Chen", title: "VP of Sales" },
      { name: "Daniel Wu", title: "CRO" },
    ],
  },
  {
    id: "acc_2",
    name: "Softonic",
    domain: "softonic.com",
    industry: "B2B SaaS",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Austin, TX",
    logoColor: "#008BE6",
    tier: "Mid-market",
    healthScore: 79,
    openDeals: 1,
    pipeline: 88000,
    contacts: 4,
    ownerId: "rep_2",
    lastActivity: "2026-06-15T18:05:00Z",
    about: "Evaluating tools to improve pipeline forecasting accuracy.",
    signals: ["Evaluating CRM add-ons", "Attended webinar"],
    keyExecutives: [{ name: "Marcus Riley", title: "Head of RevOps" }],
  },
  {
    id: "acc_3",
    name: "Clarity AI",
    domain: "clarity.ai",
    industry: "Sustainability & Fintech",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "Boston, MA",
    logoColor: "#1F6FEB",
    tier: "Enterprise",
    healthScore: 92,
    openDeals: 1,
    pipeline: 210000,
    contacts: 3,
    ownerId: "rep_1",
    lastActivity: "2026-06-17T08:10:00Z",
    about: "New CRO building a modern outbound motion from scratch.",
    signals: ["New CRO in role", "Series C funding", "Expanding GTM"],
    keyExecutives: [{ name: "Aisha Khan", title: "Chief Revenue Officer" }],
  },
  {
    id: "acc_4",
    name: "Criteo",
    domain: "criteo.com",
    industry: "AdTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Palo Alto, CA",
    logoColor: "#F7901E",
    tier: "Mid-market",
    healthScore: 84,
    openDeals: 1,
    pipeline: 120000,
    contacts: 5,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T09:15:00Z",
    about: "Scaling the sales team 2x this year; champion looped in procurement.",
    signals: ["Demo completed", "Procurement engaged"],
    keyExecutives: [{ name: "Wei Zhang", title: "Head of Sales" }],
  },
  {
    id: "acc_5",
    name: "Edicom",
    domain: "edicomgroup.com",
    industry: "B2B SaaS / EDI",
    employees: "1000-5000",
    revenue: "$500M-$1B",
    location: "Chicago, IL",
    logoColor: "#E2001A",
    tier: "Enterprise",
    healthScore: 61,
    openDeals: 1,
    pipeline: 95000,
    contacts: 2,
    ownerId: "rep_4",
    lastActivity: "2026-06-14T10:00:00Z",
    about: "Skeptical buyer; needs a strong ROI case before advancing.",
    signals: ["Opened 3 emails", "Clicked case study"],
    keyExecutives: [{ name: "Diego Fernández", title: "Sales Director" }],
  },
  {
    id: "acc_6",
    name: "Betterfly",
    domain: "betterfly.com",
    industry: "InsurTech & Wellbeing",
    employees: "5000+",
    revenue: "$1B+",
    location: "Charlotte, NC",
    logoColor: "#00C2A8",
    tier: "Enterprise",
    healthScore: 90,
    openDeals: 1,
    pipeline: 320000,
    contacts: 4,
    ownerId: "rep_4",
    lastActivity: "2026-06-17T05:30:00Z",
    about: "Digital transformation initiative with approved tooling budget.",
    signals: ["Digital transformation", "Budget approved"],
    keyExecutives: [{ name: "Grace Liu", title: "COO" }],
  },
  {
    id: "acc_7",
    name: "Talent Garden",
    domain: "talentgarden.com",
    industry: "Education & Coworking",
    employees: "50-200",
    revenue: "$10M-$50M",
    location: "Seattle, WA",
    logoColor: "#FF4E00",
    tier: "SMB",
    healthScore: 70,
    openDeals: 1,
    pipeline: 42000,
    contacts: 3,
    ownerId: "rep_3",
    lastActivity: "2026-06-13T16:40:00Z",
    about: "Demand gen lead interested in pipeline attribution.",
    signals: ["Downloaded report", "Followed company page"],
    keyExecutives: [{ name: "Priya Nair", title: "Demand Gen Lead" }],
  },
  {
    id: "acc_8",
    name: "Product Hackers",
    domain: "producthackers.com",
    industry: "Growth Marketing",
    employees: "50-200",
    revenue: "$10M-$50M",
    location: "Denver, CO",
    logoColor: "#6D28D9",
    tier: "SMB",
    healthScore: 82,
    openDeals: 1,
    pipeline: 38000,
    contacts: 2,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T20:00:00Z",
    about: "Hands-on founder wants to give his small team AI leverage.",
    signals: ["Replied positively", "Booked demo"],
    keyExecutives: [{ name: "Tom Becker", title: "Founder & CEO" }],
  },
  {
    id: "acc_9",
    name: "Primer",
    domain: "primer.io",
    industry: "FinTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "London, UK",
    logoColor: "#1A1A2E",
    tier: "Mid-market",
    healthScore: 80,
    openDeals: 1,
    pipeline: 74000,
    contacts: 3,
    ownerId: "rep_2",
    lastActivity: "2026-06-14T11:00:00Z",
    about: "Unified payment infrastructure. VP of Growth is evaluating outbound tools.",
    signals: ["Hired SDRs", "Series B funding"],
    keyExecutives: [{ name: "Oliver Watts", title: "VP of Growth" }],
  },
  {
    id: "acc_10",
    name: "Talkdesk",
    domain: "talkdesk.com",
    industry: "Customer Experience",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "San Francisco, CA",
    logoColor: "#0057FF",
    tier: "Enterprise",
    healthScore: 76,
    openDeals: 1,
    pipeline: 115000,
    contacts: 4,
    ownerId: "rep_1",
    lastActivity: "2026-06-17T04:00:00Z",
    about: "CCaaS leader expanding enterprise sales team.",
    signals: ["Series D", "Hiring AEs"],
    keyExecutives: [{ name: "Mei Lin", title: "Director of Sales" }],
  },
  {
    id: "acc_11",
    name: "VTEX",
    domain: "vtex.com",
    industry: "eCommerce",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "New York, NY",
    logoColor: "#F71963",
    tier: "Enterprise",
    healthScore: 88,
    openDeals: 1,
    pipeline: 195000,
    contacts: 5,
    ownerId: "rep_1",
    lastActivity: "2026-06-15T09:30:00Z",
    about: "Building data-driven outbound for North American GTM.",
    signals: ["Replied positively", "NYSE-listed"],
    keyExecutives: [{ name: "Rafael Santos", title: "Chief Revenue Officer" }],
  },
  {
    id: "acc_12",
    name: "Brex",
    domain: "brex.com",
    industry: "FinTech",
    employees: "500-1000",
    revenue: "$250M-$500M",
    location: "San Francisco, CA",
    logoColor: "#FC5200",
    tier: "Enterprise",
    healthScore: 73,
    openDeals: 1,
    pipeline: 132000,
    contacts: 3,
    ownerId: "rep_2",
    lastActivity: "2026-06-13T15:00:00Z",
    about: "RevOps team evaluating outreach platform alternatives.",
    signals: ["Evaluating tools", "Opened emails"],
    keyExecutives: [{ name: "Hannah Park", title: "Sales Operations Lead" }],
  },
  {
    id: "acc_13",
    name: "Typeform",
    domain: "typeform.com",
    industry: "B2B SaaS",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Barcelona, Spain",
    logoColor: "#262627",
    tier: "Mid-market",
    healthScore: 85,
    openDeals: 1,
    pipeline: 89000,
    contacts: 4,
    ownerId: "rep_3",
    lastActivity: "2026-06-16T16:00:00Z",
    about: "Scaling outbound motion in Europe and US; demo completed.",
    signals: ["Demo completed", "Multi-stakeholder"],
    keyExecutives: [{ name: "James Thornton", title: "Head of Revenue" }],
  },
  {
    id: "acc_14",
    name: "GoTo",
    domain: "goto.com",
    industry: "B2B SaaS",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "Boston, MA",
    logoColor: "#0066CC",
    tier: "Enterprise",
    healthScore: 86,
    openDeals: 1,
    pipeline: 175000,
    contacts: 6,
    ownerId: "rep_1",
    lastActivity: "2026-06-15T14:00:00Z",
    about: "Post-merger GTM overhaul; CSO evaluating full outbound stack.",
    signals: ["Replied positively", "Post-merger"],
    keyExecutives: [{ name: "George Miller", title: "Chief Sales Officer" }],
  },
  {
    id: "acc_15",
    name: "Klarna",
    domain: "klarna.com",
    industry: "FinTech",
    employees: "1000-5000",
    revenue: "$500M-$1B",
    location: "Stockholm, Sweden",
    logoColor: "#FFB3C7",
    tier: "Enterprise",
    healthScore: 69,
    openDeals: 1,
    pipeline: 98000,
    contacts: 3,
    ownerId: "rep_4",
    lastActivity: "2026-06-11T13:00:00Z",
    about: "B2B sales tech stack evaluation in progress.",
    signals: ["Evaluating CRM tools", "Opened email"],
    keyExecutives: [{ name: "Ingrid Larsen", title: "Revenue Operations Manager" }],
  },
  {
    id: "acc_16",
    name: "Kavak",
    domain: "kavak.com",
    industry: "Automotive",
    employees: "1000-5000",
    revenue: "$500M-$1B",
    location: "Mexico City, Mexico",
    logoColor: "#00A86B",
    tier: "Enterprise",
    healthScore: 78,
    openDeals: 1,
    pipeline: 155000,
    contacts: 4,
    ownerId: "rep_3",
    lastActivity: "2026-06-17T01:00:00Z",
    about: "Scaling B2B partnerships across Latin America.",
    signals: ["Series D funding", "Expanding"],
    keyExecutives: [{ name: "Carlos Mendez", title: "VP Sales LATAM" }],
  },
  {
    id: "acc_17",
    name: "Notion",
    domain: "notion.so",
    industry: "Productivity",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "San Francisco, CA",
    logoColor: "#000000",
    tier: "Enterprise",
    healthScore: 84,
    openDeals: 1,
    pipeline: 112000,
    contacts: 5,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T12:00:00Z",
    about: "Expanding enterprise partner network; legal team intro scheduled.",
    signals: ["Demo completed", "Multi-stakeholder"],
    keyExecutives: [{ name: "Zoe Thompson", title: "Head of Partnerships" }],
  },
  {
    id: "acc_18",
    name: "Adevinta",
    domain: "adevinta.com",
    industry: "Marketplaces",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "Barcelona, Spain",
    logoColor: "#0A2E71",
    tier: "Enterprise",
    healthScore: 71,
    openDeals: 1,
    pipeline: 105000,
    contacts: 3,
    ownerId: "rep_4",
    lastActivity: "2026-06-10T11:00:00Z",
    about: "Digital marketplace sales across 15 European markets.",
    signals: ["Opened emails", "Hiring in sales"],
    keyExecutives: [{ name: "Alejandro Reyes", title: "Sales Director" }],
  },
  {
    id: "acc_19",
    name: "Voi",
    domain: "voiscooters.com",
    industry: "MicroMobility",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "Stockholm, Sweden",
    logoColor: "#00C8FF",
    tier: "Mid-market",
    healthScore: 91,
    openDeals: 1,
    pipeline: 87000,
    contacts: 3,
    ownerId: "rep_2",
    lastActivity: "2026-06-17T00:00:00Z",
    about: "First CRO hire; mandate to build predictable outbound pipeline.",
    signals: ["New CRO", "Series E funding"],
    keyExecutives: [{ name: "Nina Johansson", title: "Chief Revenue Officer" }],
  },
  {
    id: "acc_20",
    name: "Conekta",
    domain: "conekta.com",
    industry: "FinTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Mexico City, Mexico",
    logoColor: "#5B2ECC",
    tier: "Mid-market",
    healthScore: 77,
    openDeals: 1,
    pipeline: 63000,
    contacts: 3,
    ownerId: "rep_3",
    lastActivity: "2026-06-12T14:00:00Z",
    about: "Scaling SMB sales team. Looking for modern outbound tools.",
    signals: ["Opened email", "Clicked case study"],
    keyExecutives: [{ name: "Sofia Martinez", title: "VP of Sales" }],
  },
  {
    id: "acc_21",
    name: "Remote",
    domain: "remote.com",
    industry: "HR Technology",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "San Francisco, CA",
    logoColor: "#3C55F0",
    tier: "Mid-market",
    healthScore: 82,
    openDeals: 1,
    pipeline: 96000,
    contacts: 4,
    ownerId: "rep_1",
    lastActivity: "2026-06-17T07:00:00Z",
    about: "Running PLG and outbound growth experiments.",
    signals: ["Hiring growth engineers", "Visited product page"],
    keyExecutives: [{ name: "Luke Henderson", title: "Head of Growth" }],
  },
  {
    id: "acc_22",
    name: "Flutterwave",
    domain: "flutterwave.com",
    industry: "FinTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Lagos, Nigeria",
    logoColor: "#E47011",
    tier: "Mid-market",
    healthScore: 68,
    openDeals: 1,
    pipeline: 51000,
    contacts: 2,
    ownerId: "rep_4",
    lastActivity: "2026-06-11T10:00:00Z",
    about: "Growing enterprise pipeline in West Africa.",
    signals: ["Opened email", "Hiring SDRs"],
    keyExecutives: [{ name: "Amara Osei", title: "Sales Manager" }],
  },
  {
    id: "acc_23",
    name: "Personio",
    domain: "personio.com",
    industry: "HR Technology",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "Munich, Germany",
    logoColor: "#1E3A5F",
    tier: "Enterprise",
    healthScore: 83,
    openDeals: 1,
    pipeline: 148000,
    contacts: 5,
    ownerId: "rep_2",
    lastActivity: "2026-06-16T09:00:00Z",
    about: "Pan-European HR SaaS scaling its outbound GTM.",
    signals: ["Series E", "Hiring AEs across DACH"],
    keyExecutives: [{ name: "Anna Weber", title: "VP Sales DACH" }],
  },
  {
    id: "acc_24",
    name: "Celonis",
    domain: "celonis.com",
    industry: "Process Mining",
    employees: "1000-5000",
    revenue: "$500M-$1B",
    location: "New York, NY",
    logoColor: "#FF7800",
    tier: "Enterprise",
    healthScore: 79,
    openDeals: 1,
    pipeline: 220000,
    contacts: 6,
    ownerId: "rep_1",
    lastActivity: "2026-06-15T13:00:00Z",
    about: "Enterprise process mining with strong SAP integration.",
    signals: ["Unicorn valuation", "Expansion hiring"],
    keyExecutives: [{ name: "Mark Jensen", title: "CRO" }],
  },
  {
    id: "acc_25",
    name: "Pipefy",
    domain: "pipefy.com",
    industry: "Process Automation",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "São Paulo, Brazil",
    logoColor: "#4F46E5",
    tier: "Mid-market",
    healthScore: 74,
    openDeals: 1,
    pipeline: 67000,
    contacts: 3,
    ownerId: "rep_3",
    lastActivity: "2026-06-14T10:00:00Z",
    about: "No-code process automation scaling into enterprise.",
    signals: ["Series C", "US expansion"],
    keyExecutives: [{ name: "Laura Silva", title: "Head of Sales" }],
  },
  {
    id: "acc_26",
    name: "Hotmart",
    domain: "hotmart.com",
    industry: "Creator Economy",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "Belo Horizonte, Brazil",
    logoColor: "#FF3D00",
    tier: "Mid-market",
    healthScore: 72,
    openDeals: 1,
    pipeline: 78000,
    contacts: 3,
    ownerId: "rep_4",
    lastActivity: "2026-06-13T11:00:00Z",
    about: "Creator monetization platform expanding B2B sales.",
    signals: ["Unicorn status", "Hiring sales team"],
    keyExecutives: [{ name: "Paulo Mello", title: "VP Sales" }],
  },
  {
    id: "acc_27",
    name: "Spendesk",
    domain: "spendesk.com",
    industry: "FinTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Paris, France",
    logoColor: "#5C1AC9",
    tier: "Mid-market",
    healthScore: 75,
    openDeals: 1,
    pipeline: 58000,
    contacts: 3,
    ownerId: "rep_2",
    lastActivity: "2026-06-12T15:00:00Z",
    about: "Spend management SaaS building EMEA outbound pipeline.",
    signals: ["Series C", "EMEA expansion"],
    keyExecutives: [{ name: "Claire Dupont", title: "Sales Director" }],
  },
  {
    id: "acc_28",
    name: "Factorial",
    domain: "factorialhr.com",
    industry: "HR Technology",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Barcelona, Spain",
    logoColor: "#7B61FF",
    tier: "Mid-market",
    healthScore: 70,
    openDeals: 1,
    pipeline: 49000,
    contacts: 2,
    ownerId: "rep_3",
    lastActivity: "2026-06-11T14:00:00Z",
    about: "HR software for SMBs looking to scale outbound in new markets.",
    signals: ["Series C", "Hiring SDRs"],
    keyExecutives: [{ name: "Jordi Romero", title: "CEO" }],
  },
  {
    id: "acc_29",
    name: "Yousign",
    domain: "yousign.com",
    industry: "LegalTech",
    employees: "50-200",
    revenue: "$10M-$50M",
    location: "Paris, France",
    logoColor: "#0FA3B1",
    tier: "SMB",
    healthScore: 66,
    openDeals: 1,
    pipeline: 34000,
    contacts: 2,
    ownerId: "rep_4",
    lastActivity: "2026-06-10T10:00:00Z",
    about: "eSignature SaaS competing with DocuSign in Europe.",
    signals: ["Series B", "Expanding sales team"],
    keyExecutives: [{ name: "Luc Martin", title: "Head of Sales" }],
  },
  {
    id: "acc_30",
    name: "Aircall",
    domain: "aircall.io",
    industry: "Cloud Telephony",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "New York, NY",
    logoColor: "#00B9F2",
    tier: "Mid-market",
    healthScore: 81,
    openDeals: 1,
    pipeline: 93000,
    contacts: 4,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T08:00:00Z",
    about: "Cloud call center solution, integrates with major CRMs.",
    signals: ["Series D", "US expansion"],
    keyExecutives: [{ name: "Jonathan Anguelov", title: "Co-CEO" }],
  },
]

export const deals: Deal[] = [
  {
    id: "deal_1",
    name: "Clarity AI — Platform",
    accountId: "acc_3",
    ownerId: "rep_1",
    stage: "negotiation",
    value: 210000,
    probability: 70,
    closeDate: "2026-06-30T00:00:00Z",
    createdAt: "2026-05-01T00:00:00Z",
    contactName: "Aisha Khan",
  },
  {
    id: "deal_2",
    name: "Betterfly — Enterprise",
    accountId: "acc_6",
    ownerId: "rep_4",
    stage: "proposal",
    value: 320000,
    probability: 55,
    closeDate: "2026-07-15T00:00:00Z",
    createdAt: "2026-05-10T00:00:00Z",
    contactName: "Grace Liu",
  },
  {
    id: "deal_3",
    name: "Fever — Team plan",
    accountId: "acc_1",
    ownerId: "rep_1",
    stage: "qualified",
    value: 95000,
    probability: 40,
    closeDate: "2026-07-05T00:00:00Z",
    createdAt: "2026-06-01T00:00:00Z",
    contactName: "Sarah Chen",
  },
  {
    id: "deal_4",
    name: "Criteo — Scale",
    accountId: "acc_4",
    ownerId: "rep_1",
    stage: "proposal",
    value: 120000,
    probability: 60,
    closeDate: "2026-06-28T00:00:00Z",
    createdAt: "2026-05-20T00:00:00Z",
    contactName: "Wei Zhang",
  },
  {
    id: "deal_5",
    name: "Softonic — RevOps",
    accountId: "acc_2",
    ownerId: "rep_2",
    stage: "qualified",
    value: 88000,
    probability: 45,
    closeDate: "2026-07-10T00:00:00Z",
    createdAt: "2026-05-25T00:00:00Z",
    contactName: "Marcus Riley",
  },
  {
    id: "deal_6",
    name: "Edicom — Pilot",
    accountId: "acc_5",
    ownerId: "rep_4",
    stage: "lead",
    value: 95000,
    probability: 20,
    closeDate: "2026-08-01T00:00:00Z",
    createdAt: "2026-06-05T00:00:00Z",
    contactName: "Diego Fernández",
  },
  {
    id: "deal_7",
    name: "Talent Garden — Starter",
    accountId: "acc_7",
    ownerId: "rep_3",
    stage: "lead",
    value: 42000,
    probability: 25,
    closeDate: "2026-07-20T00:00:00Z",
    createdAt: "2026-06-08T00:00:00Z",
    contactName: "Priya Nair",
  },
  {
    id: "deal_8",
    name: "Product Hackers — SMB",
    accountId: "acc_8",
    ownerId: "rep_1",
    stage: "won",
    value: 38000,
    probability: 100,
    closeDate: "2026-06-12T00:00:00Z",
    createdAt: "2026-05-15T00:00:00Z",
    contactName: "Tom Becker",
  },
  {
    id: "deal_9",
    name: "Shakers — Team",
    accountId: "acc_7",
    ownerId: "rep_5",
    stage: "negotiation",
    value: 64000,
    probability: 65,
    closeDate: "2026-06-29T00:00:00Z",
    createdAt: "2026-05-18T00:00:00Z",
    contactName: "Nadia Ahmed",
  },
  {
    id: "deal_10",
    name: "Viajes El Corte Inglés — Pilot",
    accountId: "acc_5",
    ownerId: "rep_4",
    stage: "lead",
    value: 70000,
    probability: 15,
    closeDate: "2026-08-10T00:00:00Z",
    createdAt: "2026-06-10T00:00:00Z",
    contactName: "James O'Connor",
  },
]

export const emailTemplates: EmailTemplate[] = [
  {
    id: "tpl_1",
    name: "Cold outreach — RevOps angle",
    folder: "Cold outreach",
    channel: "email",
    subject: "Cleaner pipeline data at {{company}}",
    body: "Hi {{first_name}},\n\nRevOps teams at companies like {{company}} use Kombo to auto-enrich and sync prospect data straight into the CRM — no manual entry.\n\nWorth a quick look?\n\nBest,\n{{sender}}",
    sent: 412,
    replyRate: 21.3,
    updatedAt: "2026-06-14T00:00:00Z",
    tags: ["RevOps", "ICP"],
  },
  {
    id: "tpl_2",
    name: "Cold outreach — Scaling SDRs",
    folder: "Cold outreach",
    channel: "email",
    subject: "{{first_name}}, scaling outbound at {{company}}",
    body: "Hi {{first_name}},\n\nNoticed {{company}} is expanding the GTM team. We help revenue leaders build qualified pipeline 3x faster with AI-assisted prospecting.\n\nOpen to a 15-min chat?",
    sent: 388,
    replyRate: 18.7,
    updatedAt: "2026-06-10T00:00:00Z",
    tags: ["Outbound"],
  },
  {
    id: "tpl_3",
    name: "Follow-up — Case study",
    folder: "Follow-up",
    channel: "email",
    subject: "Re: {{company}}",
    body: "Quick bump — sharing a 2-min case study from a team similar to {{company}} that saw a 3x lift in reply rates.",
    sent: 256,
    replyRate: 12.1,
    updatedAt: "2026-06-09T00:00:00Z",
    tags: ["Follow-up"],
  },
  {
    id: "tpl_4",
    name: "Break-up email",
    folder: "Follow-up",
    channel: "email",
    subject: "Closing the loop, {{first_name}}",
    body: "Hi {{first_name}}, I haven't heard back so I'll assume the timing isn't right. If things change, I'm one reply away.",
    sent: 174,
    replyRate: 9.4,
    updatedAt: "2026-06-02T00:00:00Z",
    tags: ["Break-up"],
  },
  {
    id: "tpl_5",
    name: "LinkedIn connection note",
    folder: "LinkedIn",
    channel: "linkedin",
    subject: "",
    body: "Hi {{first_name}}, loved your recent post on {{topic}}. Building something that could help {{company}}'s {{department}} team — would love to connect.",
    sent: 521,
    replyRate: 27.8,
    updatedAt: "2026-06-13T00:00:00Z",
    tags: ["LinkedIn", "Top performer"],
  },
  {
    id: "tpl_6",
    name: "Re-engagement — Closed lost",
    folder: "Re-engagement",
    channel: "email",
    subject: "New for {{company}} since we last spoke",
    body: "Hi {{first_name}}, a lot has changed since we last spoke. We shipped a few things that address exactly what you flagged. Worth another look?",
    sent: 98,
    replyRate: 14.6,
    updatedAt: "2026-05-28T00:00:00Z",
    tags: ["Re-engagement"],
  },
]

export const tasks: Task[] = [
  {
    id: "task_1",
    title: "Send security docs to Wei Zhang",
    type: "email",
    prospectId: "p_9",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T15:00:00Z",
    done: false,
    priority: "high",
  },
  {
    id: "task_2",
    title: "Follow up with Sarah Chen on meeting times",
    type: "follow_up",
    prospectId: "p_1",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T16:30:00Z",
    done: false,
    priority: "high",
  },
  {
    id: "task_3",
    title: "Connect with Grace Liu on LinkedIn",
    type: "linkedin",
    prospectId: "p_12",
    ownerId: "rep_4",
    assignedById: "u_1",
    dueDate: "2026-06-17T18:00:00Z",
    done: false,
    priority: "medium",
  },
  {
    id: "task_4",
    title: "Call Diego Fernández — ROI discussion",
    type: "call",
    prospectId: "p_4",
    ownerId: "rep_4",
    assignedById: "rep_1",
    dueDate: "2026-06-18T14:00:00Z",
    done: false,
    priority: "medium",
  },
  {
    id: "task_5",
    title: "Send demo link to Tom Becker",
    type: "email",
    prospectId: "p_6",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T12:00:00Z",
    done: true,
    priority: "high",
  },
  {
    id: "task_6",
    title: "Prep call notes for Softonic",
    type: "follow_up",
    prospectId: "p_2",
    ownerId: "rep_2",
    assignedById: "system",
    dueDate: "2026-06-18T09:00:00Z",
    done: false,
    priority: "low",
  },
]

export const notifications: NotificationItem[] = [
  {
    id: "n_1",
    type: "reply",
    title: "Sarah Chen replied",
    body: "“Yes, this is timely. We're hiring 5 SDRs this quarter…”",
    timestamp: "2026-06-16T14:20:00Z",
    read: false,
  },
  {
    id: "n_2",
    type: "meeting",
    title: "Meeting booked with Marcus Riley",
    body: "Tuesday 2:00 PM — Forecasting accuracy at Softonic",
    timestamp: "2026-06-15T18:05:00Z",
    read: false,
  },
  {
    id: "n_3",
    type: "deal",
    title: "Deal moved to Negotiation",
    body: "Clarity AI — Platform ($210K) advanced by Maya Patel",
    timestamp: "2026-06-16T11:00:00Z",
    read: false,
  },
  {
    id: "n_4",
    type: "mention",
    title: "Nina Kowalski mentioned you",
    body: "“@kevin can you review the Shakers sequence?”",
    timestamp: "2026-06-16T09:30:00Z",
    read: true,
  },
  {
    id: "n_5",
    type: "system",
    title: "Weekly digest ready",
    body: "Team booked 23 meetings and influenced $412K in pipeline.",
    timestamp: "2026-06-16T07:00:00Z",
    read: true,
  },
]

// Helpers
// Live binding kept current by the store so getAccount reflects edits.
let liveAccounts: Account[] = accounts
export function setLiveAccounts(next: Account[]): void {
  liveAccounts = next
}

export function getAccount(id: string): Account | undefined {
  return liveAccounts.find((a) => a.id === id)
}

// Live references kept in sync by the data store (src/lib/store.ts).
let liveDeals: Deal[] = deals
let liveTasks: Task[] = tasks
let liveTemplates: EmailTemplate[] = emailTemplates

export function setLiveDeals(next: Deal[]): void {
  liveDeals = next
}
export function setLiveTasks(next: Task[]): void {
  liveTasks = next
}
export function setLiveTemplates(next: EmailTemplate[]): void {
  liveTemplates = next
}
export function getDeal(id: string): Deal | undefined {
  return liveDeals.find((d) => d.id === id)
}
export function getTemplate(id: string): EmailTemplate | undefined {
  return liveTemplates.find((t) => t.id === id)
}
export function getTask(id: string): Task | undefined {
  return liveTasks.find((t) => t.id === id)
}

export const DEAL_STAGES: { key: Deal["stage"]; label: string }[] = [
  { key: "lead", label: "Lead" },
  { key: "qualified", label: "Qualified" },
  { key: "proposal", label: "Proposal" },
  { key: "negotiation", label: "Negotiation" },
  { key: "won", label: "Won" },
]
