import type {
  Account,
  Deal,
  EmailTemplate,
  NotificationItem,
  Task,
} from "./types"
import { generateAccounts } from "./mock-bulk"

export const accounts: Account[] = [
  {
    id: "acc_1",
    name: "Fever",
    domain: "feverup.com",
    industry: "Entertainment & Events",
    employees: "500-1000",
    revenue: "$100M-$250M",
    location: "San Francisco, CA",
    logoColor: "#E5006D",
    tier: "Enterprise",
    healthScore: 88,
    openDeals: 2,
    pipeline: 145000,
    contacts: 6,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T14:20:00Z",
    about:
      "Scaling their outbound motion with a new SDR team. Strong champion in the VP of Sales.",
    signals: ["Hiring SDRs", "Visited pricing page", "Series C funding"],
    keyExecutives: [
      { name: "Sarah Chen", title: "VP of Sales" },
      { name: "Daniel Wu", title: "CRO" },
    ],
  },
  {
    id: "acc_2",
    name: "Softonic",
    domain: "softonic.com",
    industry: "B2B SaaS",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Austin, TX",
    logoColor: "#008BE6",
    tier: "Mid-market",
    healthScore: 79,
    openDeals: 1,
    pipeline: 88000,
    contacts: 4,
    ownerId: "rep_2",
    lastActivity: "2026-06-15T18:05:00Z",
    about: "Evaluating tools to improve pipeline forecasting accuracy.",
    signals: ["Evaluating CRM add-ons", "Attended webinar"],
    keyExecutives: [{ name: "Marcus Riley", title: "Head of RevOps" }],
  },
  {
    id: "acc_3",
    name: "Clarity AI",
    domain: "clarity.ai",
    industry: "Sustainability & Fintech",
    employees: "1000-5000",
    revenue: "$250M-$500M",
    location: "Boston, MA",
    logoColor: "#1F6FEB",
    tier: "Enterprise",
    healthScore: 92,
    openDeals: 1,
    pipeline: 210000,
    contacts: 3,
    ownerId: "rep_1",
    lastActivity: "2026-06-17T08:10:00Z",
    about: "New CRO building a modern outbound motion from scratch.",
    signals: ["New CRO in role", "Series C funding", "Expanding GTM"],
    keyExecutives: [{ name: "Aisha Khan", title: "Chief Revenue Officer" }],
  },
  {
    id: "acc_4",
    name: "Criteo",
    domain: "criteo.com",
    industry: "AdTech",
    employees: "200-500",
    revenue: "$50M-$100M",
    location: "Palo Alto, CA",
    logoColor: "#F7901E",
    tier: "Mid-market",
    healthScore: 84,
    openDeals: 1,
    pipeline: 120000,
    contacts: 5,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T09:15:00Z",
    about: "Scaling the sales team 2x this year; champion looped in procurement.",
    signals: ["Demo completed", "Procurement engaged"],
    keyExecutives: [{ name: "Wei Zhang", title: "Head of Sales" }],
  },
  {
    id: "acc_5",
    name: "Edicom",
    domain: "edicomgroup.com",
    industry: "B2B SaaS / EDI",
    employees: "1000-5000",
    revenue: "$500M-$1B",
    location: "Chicago, IL",
    logoColor: "#E2001A",
    tier: "Enterprise",
    healthScore: 61,
    openDeals: 1,
    pipeline: 95000,
    contacts: 2,
    ownerId: "rep_4",
    lastActivity: "2026-06-14T10:00:00Z",
    about: "Skeptical buyer; needs a strong ROI case before advancing.",
    signals: ["Opened 3 emails", "Clicked case study"],
    keyExecutives: [{ name: "Diego Fernández", title: "Sales Director" }],
  },
  {
    id: "acc_6",
    name: "Betterfly",
    domain: "betterfly.com",
    industry: "InsurTech & Wellbeing",
    employees: "5000+",
    revenue: "$1B+",
    location: "Charlotte, NC",
    logoColor: "#00C2A8",
    tier: "Enterprise",
    healthScore: 90,
    openDeals: 1,
    pipeline: 320000,
    contacts: 4,
    ownerId: "rep_4",
    lastActivity: "2026-06-17T05:30:00Z",
    about: "Digital transformation initiative with approved tooling budget.",
    signals: ["Digital transformation", "Budget approved"],
    keyExecutives: [{ name: "Grace Liu", title: "COO" }],
  },
  {
    id: "acc_7",
    name: "Talent Garden",
    domain: "talentgarden.com",
    industry: "Education & Coworking",
    employees: "50-200",
    revenue: "$10M-$50M",
    location: "Seattle, WA",
    logoColor: "#FF4E00",
    tier: "SMB",
    healthScore: 70,
    openDeals: 1,
    pipeline: 42000,
    contacts: 3,
    ownerId: "rep_3",
    lastActivity: "2026-06-13T16:40:00Z",
    about: "Demand gen lead interested in pipeline attribution.",
    signals: ["Downloaded report", "Followed company page"],
    keyExecutives: [{ name: "Priya Nair", title: "Demand Gen Lead" }],
  },
  {
    id: "acc_8",
    name: "Product Hackers",
    domain: "producthackers.com",
    industry: "Growth Marketing",
    employees: "50-200",
    revenue: "$10M-$50M",
    location: "Denver, CO",
    logoColor: "#6D28D9",
    tier: "SMB",
    healthScore: 82,
    openDeals: 1,
    pipeline: 38000,
    contacts: 2,
    ownerId: "rep_1",
    lastActivity: "2026-06-16T20:00:00Z",
    about: "Hands-on founder wants to give his small team AI leverage.",
    signals: ["Replied positively", "Booked demo"],
    keyExecutives: [{ name: "Tom Becker", title: "Founder & CEO" }],
  },
  // Bulk procedurally-generated accounts so the Companies page is fully populated.
  ...generateAccounts(),
]

export const deals: Deal[] = [
  {
    id: "deal_1",
    name: "Clarity AI — Platform",
    accountId: "acc_3",
    ownerId: "rep_1",
    stage: "qualified",
    value: 210000,
    probability: 70,
    closeDate: "2026-06-30T00:00:00Z",
    createdAt: "2026-05-01T00:00:00Z",
    contactName: "Aisha Khan",
  },
  {
    id: "deal_2",
    name: "Betterfly — Enterprise",
    accountId: "acc_6",
    ownerId: "rep_4",
    stage: "meeting_booked",
    value: 320000,
    probability: 55,
    closeDate: "2026-07-15T00:00:00Z",
    createdAt: "2026-05-10T00:00:00Z",
    contactName: "Grace Liu",
  },
  {
    id: "deal_3",
    name: "Fever — Team plan",
    accountId: "acc_1",
    ownerId: "rep_1",
    stage: "needs_review",
    value: 95000,
    probability: 40,
    closeDate: "2026-07-05T00:00:00Z",
    createdAt: "2026-06-01T00:00:00Z",
    contactName: "Sarah Chen",
  },
  {
    id: "deal_4",
    name: "Criteo — Scale",
    accountId: "acc_4",
    ownerId: "rep_1",
    stage: "lost",
    value: 120000,
    probability: 60,
    closeDate: "2026-06-28T00:00:00Z",
    createdAt: "2026-05-20T00:00:00Z",
    contactName: "Wei Zhang",
  },
  {
    id: "deal_5",
    name: "Softonic — RevOps",
    accountId: "acc_2",
    ownerId: "rep_2",
    stage: "qualified",
    value: 88000,
    probability: 45,
    closeDate: "2026-07-10T00:00:00Z",
    createdAt: "2026-05-25T00:00:00Z",
    contactName: "Marcus Riley",
  },
  {
    id: "deal_6",
    name: "Edicom — Pilot",
    accountId: "acc_5",
    ownerId: "rep_4",
    stage: "interested",
    value: 95000,
    probability: 20,
    closeDate: "2026-08-01T00:00:00Z",
    createdAt: "2026-06-05T00:00:00Z",
    contactName: "Diego Fernández",
  },
  {
    id: "deal_7",
    name: "Talent Garden — Starter",
    accountId: "acc_7",
    ownerId: "rep_3",
    stage: "disqualified",
    value: 42000,
    probability: 25,
    closeDate: "2026-07-20T00:00:00Z",
    createdAt: "2026-06-08T00:00:00Z",
    contactName: "Priya Nair",
  },
  {
    id: "deal_8",
    name: "Product Hackers — SMB",
    accountId: "acc_8",
    ownerId: "rep_1",
    stage: "won",
    value: 38000,
    probability: 100,
    closeDate: "2026-06-12T00:00:00Z",
    createdAt: "2026-05-15T00:00:00Z",
    contactName: "Tom Becker",
  },
  {
    id: "deal_9",
    name: "Shakers — Team",
    accountId: "acc_7",
    ownerId: "rep_5",
    stage: "qualified",
    value: 64000,
    probability: 65,
    closeDate: "2026-06-29T00:00:00Z",
    createdAt: "2026-05-18T00:00:00Z",
    contactName: "Nadia Ahmed",
  },
  {
    id: "deal_10",
    name: "Viajes El Corte Inglés — Pilot",
    accountId: "acc_5",
    ownerId: "rep_4",
    stage: "not_interested",
    value: 70000,
    probability: 15,
    closeDate: "2026-08-10T00:00:00Z",
    createdAt: "2026-06-10T00:00:00Z",
    contactName: "James O'Connor",
  },
]

export const emailTemplates: EmailTemplate[] = [
  {
    id: "tpl_1",
    name: "Cold outreach — RevOps angle",
    folder: "Cold outreach",
    channel: "email",
    subject: "Cleaner pipeline data at {{company}}",
    body: "Hi {{first_name}},\n\nRevOps teams at companies like {{company}} use Kombo to auto-enrich and sync prospect data straight into the CRM — no manual entry.\n\nWorth a quick look?\n\nBest,\n{{sender}}",
    sent: 412,
    replyRate: 21.3,
    updatedAt: "2026-06-14T00:00:00Z",
    tags: ["RevOps", "ICP"],
  },
  {
    id: "tpl_2",
    name: "Cold outreach — Scaling SDRs",
    folder: "Cold outreach",
    channel: "email",
    subject: "{{first_name}}, scaling outbound at {{company}}",
    body: "Hi {{first_name}},\n\nNoticed {{company}} is expanding the GTM team. We help revenue leaders build qualified pipeline 3x faster with AI-assisted prospecting.\n\nOpen to a 15-min chat?",
    sent: 388,
    replyRate: 18.7,
    updatedAt: "2026-06-10T00:00:00Z",
    tags: ["Outbound"],
  },
  {
    id: "tpl_3",
    name: "Follow-up — Case study",
    folder: "Follow-up",
    channel: "email",
    subject: "Re: {{company}}",
    body: "Quick bump — sharing a 2-min case study from a team similar to {{company}} that saw a 3x lift in reply rates.",
    sent: 256,
    replyRate: 12.1,
    updatedAt: "2026-06-09T00:00:00Z",
    tags: ["Follow-up"],
  },
  {
    id: "tpl_4",
    name: "Break-up email",
    folder: "Follow-up",
    channel: "email",
    subject: "Closing the loop, {{first_name}}",
    body: "Hi {{first_name}}, I haven't heard back so I'll assume the timing isn't right. If things change, I'm one reply away.",
    sent: 174,
    replyRate: 9.4,
    updatedAt: "2026-06-02T00:00:00Z",
    tags: ["Break-up"],
  },
  {
    id: "tpl_5",
    name: "LinkedIn connection note",
    folder: "LinkedIn",
    channel: "linkedin",
    subject: "",
    body: "Hi {{first_name}}, loved your recent post on {{topic}}. Building something that could help {{company}}'s {{department}} team — would love to connect.",
    sent: 521,
    replyRate: 27.8,
    updatedAt: "2026-06-13T00:00:00Z",
    tags: ["LinkedIn", "Top performer"],
  },
  {
    id: "tpl_6",
    name: "Re-engagement — Closed lost",
    folder: "Re-engagement",
    channel: "email",
    subject: "New for {{company}} since we last spoke",
    body: "Hi {{first_name}}, a lot has changed since we last spoke. We shipped a few things that address exactly what you flagged. Worth another look?",
    sent: 98,
    replyRate: 14.6,
    updatedAt: "2026-05-28T00:00:00Z",
    tags: ["Re-engagement"],
  },
]

export const tasks: Task[] = [
  {
    id: "task_1",
    title: "Send security docs to Wei Zhang",
    type: "email",
    prospectId: "p_9",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T15:00:00Z",
    done: false,
    priority: "high",
  },
  {
    id: "task_2",
    title: "Follow up with Sarah Chen on meeting times",
    type: "follow_up",
    prospectId: "p_1",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T16:30:00Z",
    done: false,
    priority: "high",
  },
  {
    id: "task_3",
    title: "Connect with Grace Liu on LinkedIn",
    type: "linkedin",
    prospectId: "p_12",
    ownerId: "rep_4",
    assignedById: "u_1",
    dueDate: "2026-06-17T18:00:00Z",
    done: false,
    priority: "medium",
  },
  {
    id: "task_4",
    title: "Call Diego Fernández — ROI discussion",
    type: "call",
    prospectId: "p_4",
    ownerId: "rep_4",
    assignedById: "rep_1",
    dueDate: "2026-06-18T14:00:00Z",
    done: false,
    priority: "medium",
  },
  {
    id: "task_5",
    title: "Send demo link to Tom Becker",
    type: "email",
    prospectId: "p_6",
    ownerId: "rep_1",
    assignedById: "kai",
    dueDate: "2026-06-17T12:00:00Z",
    done: true,
    priority: "high",
  },
  {
    id: "task_6",
    title: "Prep call notes for Softonic",
    type: "follow_up",
    prospectId: "p_2",
    ownerId: "rep_2",
    assignedById: "system",
    dueDate: "2026-06-18T09:00:00Z",
    done: false,
    priority: "low",
  },
  // Assigned straight to the current user (not a rep) — seeds the Inbox's
  // "My Tasks" folder and the conversation timeline's future-item preview.
  {
    id: "task_7",
    title: "Prep talking points for Priya Nair's demo",
    type: "follow_up",
    prospectId: "p_5",
    ownerId: "u_1",
    assignedById: "kai",
    dueDate: "2026-07-15T14:00:00Z",
    done: false,
    priority: "high",
  },
]

export const notifications: NotificationItem[] = [
  {
    id: "n_1",
    type: "reply",
    title: "Sarah Chen replied",
    body: "“Yes, this is timely. We're hiring 5 SDRs this quarter…”",
    timestamp: "2026-06-16T14:20:00Z",
    read: false,
  },
  {
    id: "n_2",
    type: "meeting",
    title: "Meeting booked with Marcus Riley",
    body: "Tuesday 2:00 PM — Forecasting accuracy at Softonic",
    timestamp: "2026-06-15T18:05:00Z",
    read: false,
  },
  {
    id: "n_3",
    type: "deal",
    title: "Deal moved to Qualified",
    body: "Clarity AI — Platform ($210K) advanced by Maya Patel",
    timestamp: "2026-06-16T11:00:00Z",
    read: false,
  },
  {
    id: "n_4",
    type: "mention",
    title: "Nina Kowalski mentioned you",
    body: "“@kevin can you review the Shakers sequence?”",
    timestamp: "2026-06-16T09:30:00Z",
    read: true,
  },
  {
    id: "n_5",
    type: "system",
    title: "Weekly digest ready",
    body: "Team booked 23 meetings and influenced $412K in pipeline.",
    timestamp: "2026-06-16T07:00:00Z",
    read: true,
  },
]

// Helpers
// Live binding kept current by the store so getAccount reflects edits.
let liveAccounts: Account[] = accounts
export function setLiveAccounts(next: Account[]): void {
  liveAccounts = next
}

export function getAccount(id: string): Account | undefined {
  return liveAccounts.find((a) => a.id === id)
}

// Live references kept in sync by the data store (src/lib/store.ts).
let liveDeals: Deal[] = deals
let liveTasks: Task[] = tasks
let liveTemplates: EmailTemplate[] = emailTemplates

export function setLiveDeals(next: Deal[]): void {
  liveDeals = next
}
export function setLiveTasks(next: Task[]): void {
  liveTasks = next
}
export function setLiveTemplates(next: EmailTemplate[]): void {
  liveTemplates = next
}
export function getDeal(id: string): Deal | undefined {
  return liveDeals.find((d) => d.id === id)
}
export function getTemplate(id: string): EmailTemplate | undefined {
  return liveTemplates.find((t) => t.id === id)
}
export function getTask(id: string): Task | undefined {
  return liveTasks.find((t) => t.id === id)
}

// Ordered to match the Outcomes dropdown (lib/conv-status.ts STATUS_ORDER) —
// the app's one canonical outcome-stage ordering, top to bottom.
export const DEAL_STAGES: { key: Deal["stage"]; label: string }[] = [
  { key: "interested", label: "Interested" },
  { key: "not_interested", label: "Not interested" },
  { key: "qualified", label: "Qualified" },
  { key: "disqualified", label: "Disqualified" },
  { key: "meeting_booked", label: "Meeting booked" },
  { key: "needs_review", label: "Needs review" },
  { key: "won", label: "Won" },
  { key: "lost", label: "Lost" },
]
