import type {
  ActivityItem,
  Campaign,
  CoachRecording,
  Conversation,
  CurrentUser,
  DashboardStat,
  Integration,
  Prospect,
  ProspectList,
} from "./types"
import { generateProspects } from "./mock-bulk"

export const currentUser: CurrentUser = {
  id: "u_1",
  name: "Kevin Hawkins",
  email: "kevin@getkombo.ai",
  role: "VP of Sales",
  company: "Kombo AI",
  plan: "Scale",
  avatarColor: "#7c3aed",
}

const AVATAR_COLORS = [
  "#7c3aed",
  "#0ea5e9",
  "#f59e0b",
  "#10b981",
  "#ef4444",
  "#ec4899",
  "#6366f1",
  "#14b8a6",
]

function color(i: number) {
  return AVATAR_COLORS[i % AVATAR_COLORS.length]
}

export const prospects: Prospect[] = [
  {
    id: "p_1",
    firstName: "Sarah",
    lastName: "Chen",
    title: "VP of Sales",
    company: "Fever",
    companyDomain: "feverup.com",
    location: "San Francisco, CA",
    email: "sarah.chen@feverup.com",
    phone: "+1 415 555 0142",
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    avatarColor: color(0),
    score: 92,
    status: "replied",
    tags: ["ICP", "Decision maker"],
    lastActivity: "2026-06-16T14:20:00Z",
    addedAt: "2026-06-01T09:00:00Z",
    seniority: "VP",
    department: "Sales",
    headcount: "500-1000",
    industry: "Logistics & Supply Chain",
    revenue: "$100M-$250M",
    about:
      "Sarah leads a 40-person sales org and recently posted about scaling outbound. Strong fit for AI-assisted prospecting.",
    signals: ["Hiring SDRs", "Posted about outbound", "Visited pricing page"],
    ageRange: "35-44",
    personalityType: "D",
    companyLocation: "New York, NY",
    companyLinkedinUrl: "https://linkedin.com/company/fever",
  },
  {
    id: "p_2",
    firstName: "Marcus",
    lastName: "Riley",
    title: "Head of Revenue Operations",
    company: "Softonic",
    companyDomain: "softonic.com",
    location: "Austin, TX",
    email: "marcus@softonic.com",
    linkedinUrl: "https://linkedin.com/in/marcusriley",
    avatarColor: color(1),
    score: 87,
    status: "meeting",
    tags: ["RevOps", "Champion"],
    lastActivity: "2026-06-15T18:05:00Z",
    addedAt: "2026-05-28T11:30:00Z",
    seniority: "Director",
    department: "Operations",
    headcount: "200-500",
    industry: "B2B SaaS",
    revenue: "$50M-$100M",
    about:
      "Owns the GTM tech stack at Softonic. Evaluating tools to improve pipeline forecasting accuracy.",
    signals: ["Evaluating CRM add-ons", "Attended webinar"],
    ageRange: "30-39",
    personalityType: "C",
    companyLocation: "Barcelona, Spain",
    companyLinkedinUrl: "https://linkedin.com/company/softonic",
    outOfOffice: true,
    languages: [
      { flag: "🇪🇸", name: "Spanish" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  {
    id: "p_3",
    firstName: "Aisha",
    lastName: "Khan",
    title: "Chief Revenue Officer",
    company: "Clarity AI",
    companyDomain: "clarity.ai",
    location: "Boston, MA",
    email: "aisha.khan@clarity.ai",
    linkedinUrl: "https://linkedin.com/in/aishakhan",
    avatarColor: color(2),
    score: 95,
    status: "new",
    tags: ["ICP", "C-level"],
    lastActivity: "2026-06-17T08:10:00Z",
    addedAt: "2026-06-17T08:00:00Z",
    seniority: "C-Level",
    department: "Executive",
    headcount: "1000-5000",
    industry: "Healthcare Technology",
    revenue: "$250M-$500M",
    about:
      "New CRO at Clarity AI, mandate to build a modern outbound motion from scratch.",
    signals: ["New in role", "Funding round (Series C)", "Expanding GTM team"],
    ageRange: "40-49",
    personalityType: "D",
    companyLocation: "Madrid, Spain",
    companyLinkedinUrl: "https://linkedin.com/company/clarity-ai",
  },
  {
    id: "p_4",
    firstName: "Diego",
    lastName: "Fernández",
    title: "Sales Director",
    company: "Edicom",
    companyDomain: "edicomgroup.com",
    location: "Chicago, IL",
    email: "diego.f@edicomgroup.com",
    linkedinUrl: "https://linkedin.com/in/diegofernandez",
    avatarColor: color(3),
    score: 74,
    status: "contacted",
    tags: ["Mid-market"],
    lastActivity: "2026-06-14T10:00:00Z",
    addedAt: "2026-06-05T13:15:00Z",
    seniority: "Director",
    department: "Sales",
    headcount: "1000-5000",
    industry: "Industrial Manufacturing",
    revenue: "$500M-$1B",
    about:
      "Manages regional sales teams across North America. Skeptical buyer, needs strong ROI case.",
    signals: ["Opened 3 emails", "Clicked case study link"],
    ageRange: "38-47",
    personalityType: "C",
    companyLocation: "Valencia, Spain",
    companyLinkedinUrl: "https://linkedin.com/company/edicom",
    languages: [
      { flag: "🇪🇸", name: "Spanish" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  {
    id: "p_5",
    firstName: "Priya",
    lastName: "Nair",
    title: "Demand Generation Lead",
    company: "Talent Garden",
    companyDomain: "talentgarden.com",
    location: "Seattle, WA",
    email: "priya@talentgarden.com",
    linkedinUrl: "https://linkedin.com/in/priyanair",
    avatarColor: color(4),
    score: 68,
    status: "contacted",
    tags: ["Marketing"],
    lastActivity: "2026-06-13T16:40:00Z",
    addedAt: "2026-06-08T09:45:00Z",
    seniority: "Manager",
    department: "Marketing",
    headcount: "50-200",
    industry: "Data & Analytics",
    revenue: "$10M-$50M",
    about:
      "Runs demand gen and influences tooling decisions. Interested in pipeline attribution.",
    signals: ["Downloaded report", "Followed company page"],
    ageRange: "28-37",
    personalityType: "I",
    companyLocation: "Milan, Italy",
    companyLinkedinUrl: "https://linkedin.com/company/talent-garden",
    outOfOffice: true,
    languages: [
      { flag: "🇬🇧", name: "English" },
      { flag: "🇮🇳", name: "Hindi" },
    ],
  },
  {
    id: "p_6",
    firstName: "Tom",
    lastName: "Becker",
    title: "Founder & CEO",
    company: "Product Hackers",
    companyDomain: "producthackers.com",
    location: "Denver, CO",
    email: "tom@producthackers.com",
    linkedinUrl: "https://linkedin.com/in/tombecker",
    avatarColor: color(5),
    score: 81,
    status: "replied",
    tags: ["Founder", "ICP"],
    lastActivity: "2026-06-16T20:00:00Z",
    addedAt: "2026-06-02T08:20:00Z",
    seniority: "C-Level",
    department: "Executive",
    headcount: "50-200",
    industry: "Robotics",
    revenue: "$10M-$50M",
    about:
      "Hands-on founder selling into enterprise. Wants to give his small team leverage with AI.",
    signals: ["Replied positively", "Booked demo link"],
    ageRange: "32-41",
    personalityType: "I",
    companyLocation: "Amsterdam, Netherlands",
    companyLinkedinUrl: "https://linkedin.com/company/product-hackers",
  },
  {
    id: "p_7",
    firstName: "Elena",
    lastName: "Rossi",
    title: "VP Marketing",
    company: "Weekendesk Foods",
    companyDomain: "tavolafoods.com",
    location: "New York, NY",
    email: "elena.rossi@tavolafoods.com",
    linkedinUrl: "https://linkedin.com/in/elenarossi",
    avatarColor: color(6),
    score: 59,
    status: "not_interested",
    tags: ["Marketing"],
    lastActivity: "2026-06-10T12:00:00Z",
    addedAt: "2026-06-04T15:00:00Z",
    seniority: "VP",
    department: "Marketing",
    headcount: "200-500",
    industry: "Food & Beverage",
    revenue: "$50M-$100M",
    about: "Not a fit right now — no budget allocated for outbound tooling.",
    signals: ["Replied: not now"],
    ageRange: "36-45",
    personalityType: "S",
    companyLocation: "Paris, France",
    companyLinkedinUrl: "https://linkedin.com/company/weekendesk",
    languages: [
      { flag: "🇮🇹", name: "Italian" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  {
    id: "p_8",
    firstName: "James",
    lastName: "O'Connor",
    title: "Director of Business Development",
    company: "Viajes El Corte Inglés",
    companyDomain: "harborfin.com",
    location: "Miami, FL",
    email: "james.oconnor@harborfin.com",
    linkedinUrl: "https://linkedin.com/in/jamesoconnor",
    avatarColor: color(7),
    score: 78,
    status: "new",
    tags: ["FinServ", "ICP"],
    lastActivity: "2026-06-17T07:30:00Z",
    addedAt: "2026-06-17T07:30:00Z",
    seniority: "Director",
    department: "Business Development",
    headcount: "500-1000",
    industry: "Financial Services",
    revenue: "$100M-$250M",
    about:
      "Building out a new BD function. Looking for ways to identify in-market accounts faster.",
    signals: ["New territory", "Hiring BDRs"],
    ageRange: "33-42",
    personalityType: "D",
    companyLocation: "Madrid, Spain",
    companyLinkedinUrl: "https://linkedin.com/company/el-corte-ingles",
  },
  {
    id: "p_9",
    firstName: "Wei",
    lastName: "Zhang",
    title: "Head of Sales",
    company: "Criteo",
    companyDomain: "criteo.com",
    location: "Palo Alto, CA",
    email: "wei.zhang@criteo.com",
    linkedinUrl: "https://linkedin.com/in/weizhang",
    avatarColor: color(0),
    score: 88,
    status: "meeting",
    tags: ["ICP", "Champion"],
    lastActivity: "2026-06-16T09:15:00Z",
    addedAt: "2026-05-30T10:00:00Z",
    seniority: "VP",
    department: "Sales",
    headcount: "200-500",
    industry: "Deep Tech",
    revenue: "$50M-$100M",
    about:
      "Scaling the sales team 2x this year. Demoed Kombo and is championing internally.",
    signals: ["Demo completed", "Looped in procurement"],
    enriched: false,
    ageRange: "34-43",
    personalityType: "I",
    companyLocation: "Paris, France",
    companyLinkedinUrl: "https://linkedin.com/company/criteo",
    languages: [
      { flag: "🇨🇳", name: "Mandarin" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  {
    id: "p_10",
    firstName: "Nadia",
    lastName: "Ahmed",
    title: "Revenue Operations Manager",
    company: "Shakers Media",
    companyDomain: "skylinemedia.com",
    location: "Los Angeles, CA",
    email: "nadia.ahmed@skylinemedia.com",
    linkedinUrl: "https://linkedin.com/in/nadiaahmed",
    avatarColor: color(1),
    score: 71,
    status: "contacted",
    tags: ["RevOps"],
    lastActivity: "2026-06-12T14:00:00Z",
    addedAt: "2026-06-06T11:00:00Z",
    seniority: "Manager",
    department: "Operations",
    headcount: "200-500",
    industry: "Media & Entertainment",
    revenue: "$50M-$100M",
    about:
      "Owns CRM hygiene and reporting. Frustrated with manual data entry from reps.",
    signals: ["Opened email", "Visited integrations page"],
    enriched: false,
    ageRange: "29-38",
    personalityType: "S",
    companyLocation: "London, UK",
    companyLinkedinUrl: "https://linkedin.com/company/shakers",
  },
  {
    id: "p_11",
    firstName: "Lucas",
    lastName: "Moreau",
    title: "Enterprise Account Executive",
    company: "Nuclio Talent Cloud",
    companyDomain: "pinnaclecloud.com",
    location: "Toronto, ON",
    email: "lucas.moreau@pinnaclecloud.com",
    linkedinUrl: "https://linkedin.com/in/lucasmoreau",
    avatarColor: color(2),
    score: 64,
    status: "new",
    tags: ["Peer"],
    lastActivity: "2026-06-17T06:00:00Z",
    addedAt: "2026-06-17T06:00:00Z",
    seniority: "Individual Contributor",
    department: "Sales",
    headcount: "1000-5000",
    industry: "Cloud Infrastructure",
    revenue: "$250M-$500M",
    about: "Front-line AE who could become a bottoms-up champion for the team.",
    signals: ["Engaged on LinkedIn"],
    ageRange: "27-36",
    personalityType: "I",
    companyLocation: "Barcelona, Spain",
    companyLinkedinUrl: "https://linkedin.com/company/nuclio",
    languages: [
      { flag: "🇫🇷", name: "French" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  {
    id: "p_12",
    firstName: "Grace",
    lastName: "Liu",
    title: "Chief Operating Officer",
    company: "Betterfly",
    companyDomain: "betterfly.com",
    location: "Charlotte, NC",
    email: "grace.liu@betterfly.com",
    linkedinUrl: "https://linkedin.com/in/graceliu",
    avatarColor: color(3),
    score: 90,
    status: "new",
    tags: ["C-level", "ICP", "Enterprise"],
    lastActivity: "2026-06-17T05:30:00Z",
    addedAt: "2026-06-16T17:00:00Z",
    seniority: "C-Level",
    department: "Executive",
    headcount: "5000+",
    industry: "Banking",
    revenue: "$1B+",
    about:
      "Driving a digital transformation initiative. High-value enterprise opportunity.",
    signals: ["Digital transformation initiative", "Budget approved for tooling"],
    enriched: false,
    ageRange: "42-51",
    personalityType: "D",
    companyLocation: "Santiago, Chile",
    companyLinkedinUrl: "https://linkedin.com/company/betterfly",
    languages: [
      { flag: "🇨🇳", name: "Mandarin" },
      { flag: "🇬🇧", name: "English" },
    ],
  },
  // Bulk procedurally-generated prospects so the People page is fully populated.
  ...generateProspects(),
]

export const prospectLists: ProspectList[] = [
  {
    id: "l_1",
    name: "Q3 Enterprise ICP",
    description: "VP+ at 1000+ employee companies in our core verticals.",
    prospectIds: ["p_1", "p_3", "p_9", "p_12", "p_4"],
    createdAt: "2026-06-01T09:00:00Z",
    color: "#7c3aed",
    source: "salesnav",
    dynamic: true,
    criteria: {
      titles: ["VP Sales", "CRO", "Head of Sales"],
      seniority: ["VP", "C-Level", "Director"],
      industries: ["Software", "Fintech", "Marketplace"],
      headcount: ["1,001-5,000", "5,000+"],
      locations: ["United States", "United Kingdom", "Spain"],
      keywords: "",
      signals: ["Hiring sales roles", "Recent funding"],
    },
    enrichment: "continuous",
    newPerWeek: 12,
    campaignId: "cm_1",
    sendMode: "continuous",
    lastSyncedAt: "2026-06-17T06:00:00Z",
  },
  {
    id: "l_2",
    name: "RevOps Champions",
    description: "RevOps leaders who influence the GTM tech stack.",
    prospectIds: ["p_2", "p_10"],
    createdAt: "2026-05-28T11:00:00Z",
    color: "#0ea5e9",
    source: "search",
  },
  {
    id: "l_3",
    name: "Inbound — Pricing Page",
    description: "Prospects who visited the pricing page in the last 30 days.",
    prospectIds: ["p_1", "p_6", "p_8"],
    createdAt: "2026-06-10T14:00:00Z",
    color: "#10b981",
    source: "csv",
    dynamic: true,
    criteria: {
      titles: [],
      seniority: ["Manager", "Director", "VP"],
      industries: [],
      headcount: [],
      locations: [],
      keywords: "Visited pricing page",
      signals: ["Website intent", "Pricing-page visit"],
    },
    enrichment: "off",
    newPerWeek: 8,
    campaignId: "cm_2",
    sendMode: "continuous",
    lastSyncedAt: "2026-06-17T05:30:00Z",
  },
  {
    id: "l_4",
    name: "Founders — Seed to Series B",
    description: "Hands-on founders at early-stage companies.",
    prospectIds: ["p_6"],
    createdAt: "2026-06-12T08:00:00Z",
    color: "#f59e0b",
    source: "linkedin",
  },
  {
    id: "l_5",
    name: "Target accounts — Q3",
    description: "Named enterprise accounts the team is working this quarter.",
    prospectIds: [],
    accountIds: ["acc_1", "acc_3", "acc_4", "acc_6"],
    kind: "company",
    createdAt: "2026-06-11T08:00:00Z",
    color: "#14b8a6",
    source: "salesnav",
  },
]

export const conversations: Conversation[] = [
  // — Hot: meeting just booked (5m ago) —
  {
    id: "c_5",
    prospectId: "p_3",
    channel: "email",
    subject: "Demo — Clarity AI",
    unread: 1,
    lastMessageAt: "2026-06-23T14:55:00Z",
    status: "meeting_booked",
    aiDraft:
      "Perfect, Aisha — locking Thursday 3pm in now. Calendar invite with a Google Meet link is on its way: https://meet.google.com/kombo-demo. I'll come ready with a teardown of Clarity AI's current outbound so we hit the ground running.",
    events: [
      {
        id: "e_1",
        kind: "open",
        label: "Opened your email",
        detail: "Demo — Clarity AI",
        timestamp: "2026-06-23T13:40:00Z",
      },
      {
        id: "e_2",
        kind: "tag",
        label: "Auto-tagged as",
        status: "meeting_booked",
        timestamp: "2026-06-23T14:55:30Z",
      },
    ],
    messages: [
      {
        id: "m_10",
        channel: "email",
        direction: "outbound",
        body: "Hi Aisha — saw Clarity AI is scaling the revenue team. Want a 15-minute look at how reps cut manual prospecting to near zero from week one?",
        timestamp: "2026-06-22T16:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_11",
        channel: "email",
        direction: "inbound",
        body: "Yes, this is timely. Thursday at 3pm works on my end — send an invite and I'll bring our Head of Sales Ops.",
        timestamp: "2026-06-23T14:55:00Z",
        read: false,
      },
    ],
  },
  // — LinkedIn, interested, multi-touch sequence (21m ago) —
  {
    id: "c_2",
    prospectId: "p_6",
    channel: "linkedin",
    subject: "Product Hackers — outbound",
    unread: 1,
    lastMessageAt: "2026-06-23T14:39:00Z",
    status: "interested",
    aiDraft:
      "Love it, Tom. Quickest way to show value is a 15-min walkthrough on your real data — I'll show how Product Hackers would replace the spreadsheet shuffle. Does Thursday or Friday suit you better?",
    events: [
      {
        id: "e_3",
        kind: "connection",
        label: "Connection accepted",
        timestamp: "2026-06-22T09:10:00Z",
      },
      {
        id: "e_4",
        kind: "like",
        label: "Liked their post",
        detail: '"How we 4x\'d reply rates"',
        timestamp: "2026-06-22T09:30:00Z",
      },
    ],
    messages: [
      {
        id: "m_3",
        channel: "linkedin",
        direction: "outbound",
        body: "Tom, love what Product Hackers is building. Curious how your small team handles outbound today?",
        timestamp: "2026-06-23T11:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_4",
        channel: "linkedin",
        direction: "inbound",
        body: "Honestly it's a mess of spreadsheets. Send me a demo link and I'll take a look this week.",
        timestamp: "2026-06-23T14:39:00Z",
        read: false,
      },
    ],
  },
  // — Email, interested, hiring signal (1h ago) —
  {
    id: "c_1",
    prospectId: "p_1",
    channel: "email",
    subject: "Scaling outbound at Fever",
    unread: 1,
    lastMessageAt: "2026-06-23T14:00:00Z",
    status: "interested",
    aiDraft:
      "Great timing, Sarah — congrats on the SDR push. The fastest path is a quick 15-minute look at how new reps ramp on Fever's data from day one. I'll send a couple of times; grab whichever is easiest.",
    events: [
      {
        id: "e_5",
        kind: "click",
        label: "Clicked your pricing link",
        timestamp: "2026-06-23T13:05:00Z",
      },
    ],
    messages: [
      {
        id: "m_1",
        channel: "email",
        direction: "outbound",
        body: "Hi Sarah — saw your post about scaling the SDR team. We help reps build qualified pipeline 3x faster with AI-assisted prospecting. Worth a quick chat?",
        timestamp: "2026-06-22T10:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_2",
        channel: "email",
        direction: "inbound",
        body: "Hi Kevin — yes, this is timely. We're hiring 5 SDRs this quarter. Can you send over a few times next week?",
        timestamp: "2026-06-23T14:00:00Z",
        read: false,
      },
    ],
  },
  // — LinkedIn, interested (2h ago) —
  {
    id: "c_9",
    prospectId: "p_10",
    channel: "linkedin",
    subject: "Shakers Media — intro",
    unread: 1,
    lastMessageAt: "2026-06-23T13:10:00Z",
    status: "interested",
    aiDraft:
      "Appreciate the reply, Nadia! Happy to send a 2-minute Loom first so you can skim on your own time, then a live session if it's a fit. Want me to fire that over?",
    events: [
      {
        id: "e_6",
        kind: "connection",
        label: "Connection accepted",
        timestamp: "2026-06-23T08:00:00Z",
      },
    ],
    messages: [
      {
        id: "m_12",
        channel: "linkedin",
        direction: "outbound",
        body: "Nadia — Shakers' growth this year is hard to miss. How are you sourcing net-new accounts right now?",
        timestamp: "2026-06-23T09:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_13",
        channel: "linkedin",
        direction: "inbound",
        body: "Mostly referrals and inbound. Open to seeing how you'd help us go outbound without hiring a big team.",
        timestamp: "2026-06-23T13:10:00Z",
        read: false,
      },
    ],
  },
  // — Email, Spanish, meeting booked (3h ago) —
  {
    id: "c_3",
    prospectId: "p_2",
    channel: "email",
    subject: "Forecasting accuracy at Softonic",
    unread: 1,
    lastMessageAt: "2026-06-23T12:05:00Z",
    recipientLang: "es",
    status: "meeting_booked",
    aiDraft:
      "Genial, Marcus — el martes a las 2pm queda confirmado. Te envío la invitación con el enlace de Google Meet y los precios antes de la reunión. ¡Hablamos!",
    events: [
      {
        id: "e_7",
        kind: "tag",
        label: "Auto-tagged as",
        status: "meeting_booked",
        timestamp: "2026-06-23T12:05:30Z",
      },
    ],
    messages: [
      {
        id: "m_5",
        channel: "email",
        direction: "outbound",
        body: "Marcus — following up with the ROI breakdown we discussed. Tuesday 2pm still work?",
        timestamp: "2026-06-23T09:00:00Z",
        read: true,
        lang: "en",
        aiGenerated: true,
      },
      {
        id: "m_6",
        channel: "email",
        direction: "inbound",
        body: "Perfecto, el martes me viene bien. Llevaré a nuestro VP de Ventas. ¿Podrías enviarme también los precios antes de la reunión? Gracias.",
        timestamp: "2026-06-23T12:05:00Z",
        read: false,
        lang: "es",
      },
    ],
  },
  // — LinkedIn, interested (5h ago) —
  {
    id: "c_6",
    prospectId: "p_5",
    channel: "linkedin",
    subject: "Talent Garden — prospecting",
    unread: 0,
    lastMessageAt: "2026-06-23T10:20:00Z",
    status: "interested",
    aiDraft:
      "Thanks, Priya — that's exactly the reaction we hope for. Want me to set up a tight 20-minute session to map this to Talent Garden's workflow? I'll send a couple of times.",
    events: [
      {
        id: "e_20",
        kind: "step",
        label: "Sequence step sent",
        stepChannel: "linkedin",
        timestamp: "2026-06-23T08:00:00Z",
      },
      {
        id: "e_21",
        kind: "view",
        label: "Viewed their profile",
        timestamp: "2026-06-23T08:15:00Z",
      },
    ],
    messages: [
      {
        id: "m_14",
        channel: "linkedin",
        direction: "outbound",
        body: "Priya — built something that finds lookalikes of your best customers automatically. Thought of Talent Garden right away.",
        timestamp: "2026-06-23T08:30:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_15",
        channel: "linkedin",
        direction: "inbound",
        body: "This looks really promising — exactly the kind of thing we've been missing. Let me find time this week.",
        timestamp: "2026-06-23T10:20:00Z",
        read: true,
      },
    ],
  },
  // — LinkedIn, referred to someone else, needs review (8h ago) —
  {
    id: "c_12",
    prospectId: "p_7",
    channel: "linkedin",
    subject: "Weekendesk Foods — intro",
    unread: 1,
    lastMessageAt: "2026-06-23T07:00:00Z",
    status: "need_review",
    aiDraft:
      "Thanks for pointing me the right way, Elena — I really appreciate it. I'll reach out to your Head of Growth directly and keep you in the loop. Anything I should know before I do?",
    events: [
      {
        id: "e_8",
        kind: "tag",
        label: "Auto-tagged as",
        status: "need_review",
        timestamp: "2026-06-23T07:00:30Z",
      },
    ],
    messages: [
      {
        id: "m_16",
        channel: "linkedin",
        direction: "outbound",
        body: "Elena — are you the right person to talk to about how Weekendesk sources new B2B accounts?",
        timestamp: "2026-06-22T18:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_17",
        channel: "linkedin",
        direction: "inbound",
        body: "Not me directly — but let me intro you to Sofia, our Head of Growth. She owns this and would love to chat.",
        timestamp: "2026-06-23T07:00:00Z",
        read: false,
      },
    ],
  },
  // — Email, Spanish, bad timing → needs review (1d ago) —
  {
    id: "c_7",
    prospectId: "p_4",
    channel: "email",
    subject: "Edicom — prospecting",
    unread: 1,
    lastMessageAt: "2026-06-22T15:30:00Z",
    recipientLang: "es",
    status: "need_review",
    aiDraft:
      "Lo entiendo perfectamente, Diego — el momento lo es todo. Vuelvo a contactarte en Q4. Mientras tanto te envío un recurso breve sobre cómo equipos como Edicom se prepararon, sin compromiso.",
    events: [
      {
        id: "e_22",
        kind: "step",
        label: "Sequence step sent",
        stepChannel: "email",
        timestamp: "2026-06-22T10:30:00Z",
      },
      {
        id: "e_23",
        kind: "open",
        label: "Opened your email",
        timestamp: "2026-06-22T14:00:00Z",
      },
      {
        id: "e_24",
        kind: "click",
        label: "Clicked your link",
        timestamp: "2026-06-22T14:05:00Z",
      },
    ],
    messages: [
      {
        id: "m_18",
        channel: "email",
        direction: "outbound",
        body: "Diego — worth 15 minutes to see how Edicom could automate the manual parts of prospecting?",
        timestamp: "2026-06-22T11:00:00Z",
        read: true,
        lang: "en",
        aiGenerated: true,
      },
      {
        id: "m_19",
        channel: "email",
        direction: "inbound",
        body: "Gracias, pero ahora mismo no es buen momento. Estamos cerrando el trimestre. ¿Podemos retomarlo en Q4?",
        timestamp: "2026-06-22T15:30:00Z",
        read: false,
        lang: "es",
      },
    ],
  },
  // — Email, referral / procurement next steps (1d ago) —
  {
    id: "c_4",
    prospectId: "p_9",
    channel: "email",
    subject: "Next steps + procurement",
    unread: 0,
    lastMessageAt: "2026-06-22T09:15:00Z",
    status: "qualified",
    aiDraft:
      "Glad the demo landed, Wei. I'll send our security overview and SOC 2 report straight to procurement. Want me to set a 15-minute call with your reviewer to fast-track any questions?",
    messages: [
      {
        id: "m_7",
        channel: "email",
        direction: "inbound",
        body: "Great demo. I've looped in procurement — what does the security review look like?",
        timestamp: "2026-06-22T09:15:00Z",
        read: true,
      },
    ],
  },
  // — Email, reply queued / scheduled to send tomorrow —
  {
    id: "c_10",
    prospectId: "p_11",
    channel: "email",
    subject: "Nuclio Talent Cloud — follow-up",
    unread: 0,
    lastMessageAt: "2026-06-22T08:00:00Z",
    status: "interested",
    scheduledAt: "2026-07-09T08:00:00Z",
    aiDraft:
      "Hi Lucas — circling back as promised. I put together a short overview tailored to Nuclio; want me to send it over or jump on a quick call Thursday?",
    messages: [
      {
        id: "m_20",
        channel: "email",
        direction: "inbound",
        body: "Interesting — reach back out next week and we can find time. Slammed until then.",
        timestamp: "2026-06-22T08:00:00Z",
        read: true,
      },
    ],
  },
  // — Email, not interested, polite close (2d ago) — wrapped up and archived —
  {
    id: "c_8",
    prospectId: "p_8",
    channel: "email",
    subject: "Viajes El Corte Inglés — intro",
    unread: 0,
    lastMessageAt: "2026-06-21T16:45:00Z",
    status: "not_interested",
    archived: true,
    aiDraft:
      "Appreciate you being straight with me, James — I won't keep your inbox busy. If priorities shift, I'm one reply away. Wishing you and the team a strong quarter.",
    messages: [
      {
        id: "m_21",
        channel: "email",
        direction: "outbound",
        body: "James — quick one: is improving outbound efficiency on the roadmap at Viajes this year?",
        timestamp: "2026-06-21T10:00:00Z",
        read: true,
        aiGenerated: true,
      },
      {
        id: "m_22",
        channel: "email",
        direction: "inbound",
        body: "Thanks, but we just signed with a competitor last month. Not looking to switch right now.",
        timestamp: "2026-06-21T16:45:00Z",
        read: true,
      },
    ],
  },
  // — Email, sent — awaiting their reply (2d ago) —
  {
    id: "c_11",
    prospectId: "p_12",
    channel: "email",
    subject: "Betterfly — quick idea",
    unread: 0,
    lastMessageAt: "2026-06-21T12:30:00Z",
    messages: [
      {
        id: "m_23",
        channel: "email",
        direction: "inbound",
        body: "Hi Kevin — saw your note. Can you share a one-pager before we find time?",
        timestamp: "2026-06-21T09:00:00Z",
        read: true,
      },
      {
        id: "m_24",
        channel: "email",
        direction: "outbound",
        body: "Of course, Grace — attaching a one-pager on how Betterfly could lift reply rates. Let me know what resonates and I'll tailor a short walkthrough.",
        timestamp: "2026-06-21T12:30:00Z",
        read: true,
        aiGenerated: true,
      },
    ],
  },
]

export const campaigns: Campaign[] = [
  {
    id: "cm_1",
    name: "Enterprise CRO Outbound",
    status: "active",
    enrolled: 124,
    opened: 86,
    replied: 22,
    meetings: 7,
    createdAt: "2026-05-20T09:00:00Z",
    listId: "l_1",
    steps: [
      {
        id: "s_1",
        channel: "email",
        delayDays: 0,
        subject: "{{first_name}}, scaling outbound at {{company}}",
        body: "Hi {{first_name}}, noticed {{company}} is expanding the GTM team. We help revenue leaders build pipeline 3x faster...",
      },
      {
        id: "s_2",
        channel: "linkedin_message",
        delayDays: 2,
        body: "Connection request + short note referencing their recent post.",
      },
      {
        id: "s_3",
        channel: "email",
        delayDays: 4,
        subject: "Re: scaling outbound at {{company}}",
        body: "Quick bump — sharing a 2-min case study from a similar team.",
      },
    ],
  },
  {
    id: "cm_2",
    name: "RevOps Tool Eval",
    status: "active",
    enrolled: 58,
    opened: 41,
    replied: 12,
    meetings: 4,
    createdAt: "2026-05-25T09:00:00Z",
    listId: "l_3",
    steps: [
      {
        id: "s_4",
        channel: "email",
        delayDays: 0,
        subject: "Cleaner CRM data at {{company}}",
        body: "Hi {{first_name}}, RevOps teams use Kombo to auto-enrich and sync prospect data...",
      },
      {
        id: "s_5",
        channel: "email",
        delayDays: 3,
        subject: "Re: Cleaner CRM data",
        body: "Following up with a short Loom showing the HubSpot sync.",
      },
    ],
  },
  {
    id: "cm_3",
    name: "Founder-led (SMB)",
    status: "paused",
    enrolled: 33,
    opened: 19,
    replied: 6,
    meetings: 2,
    createdAt: "2026-06-01T09:00:00Z",
    steps: [
      {
        id: "s_6",
        channel: "linkedin_message",
        delayDays: 0,
        body: "Personalized connection request referencing their product.",
      },
    ],
  },
  {
    id: "cm_4",
    name: "Q3 Reactivation",
    status: "draft",
    enrolled: 0,
    opened: 0,
    replied: 0,
    meetings: 0,
    createdAt: "2026-06-15T09:00:00Z",
    steps: [],
  },
]

export const coachRecordings: CoachRecording[] = [
  {
    id: "r_1",
    title: "Discovery — Criteo",
    prospectName: "Wei Zhang",
    company: "Criteo",
    date: "2026-06-16T09:00:00Z",
    durationMin: 34,
    score: 88,
    talkRatio: 42,
    sentiment: "positive",
    highlights: [
      "Strong discovery on current outbound pain",
      "Clear next step booked",
      "Multi-threaded into procurement",
    ],
    nextSteps: ["Send security docs", "Schedule technical deep-dive"],
    videoSource: "meet",
    mediaKind: "video",
    summarized: true,
    analyzed: true,
    overview:
      "Wei walked through Criteo's current outbound stack and where reps lose time on manual research. Strong engagement throughout, with procurement looped in near the end.",
    scoreBreakdown: [
      {
        label: "Discovery",
        metricScore: 92,
        metricSummary: "Uncovered current tooling, team size, and specific pain points early.",
        repAvgScore: 84,
        teamAvgScore: 79,
        subMetrics: [
          {
            label: "Open-ended questions",
            score: 90,
            questions: [
              {
                text: "Did the rep ask open-ended discovery questions?",
                breakdownType: "good",
                value: "Yes",
                why: "The rep opened with \"I'd love to hear how outbound works today on your team\" — a broad, open-ended prompt rather than a leading yes/no question.",
                quotes: ["Sure. Right now our SDRs spend a lot of time just finding the right contact and verifying emails before they can even start a sequence."],
                howToImprove: "Keep stacking a second open-ended follow-up before pivoting to a closed quantifying question.",
              },
            ],
          },
          // Flagged NA as a concrete example of the "not applicable" chip —
          // renders a neutral pill instead of a (misleading) percent score.
          {
            label: "Pain quantification",
            score: 94,
            isNa: true,
            questions: [
              {
                text: "Did the rep quantify the cost of the prospect's pain?",
                breakdownType: "good",
                value: "N/A",
                isNa: true,
                why: "The prospect volunteered a concrete number before the rep needed to probe for one.",
                quotes: ["Honestly, probably a third of their week. It's a real bottleneck."],
                howToImprove: "No action needed — the quantification came from the prospect unprompted.",
              },
            ],
          },
        ],
      },
      {
        label: "Objection handling",
        metricScore: 81,
        metricSummary: "Handled the security question well; slightly rushed the pricing pushback.",
        repAvgScore: 77,
        teamAvgScore: 74,
        subMetrics: [
          {
            label: "Pricing objection",
            score: 68,
            questions: [
              {
                text: "Did the rep uncover the prospect's budget before defending price?",
                breakdownType: "medium",
                value: "Partial",
                why: "The rep answered the 40-seat minimum question directly but moved on before establishing what Criteo was already paying.",
                quotes: ["On pricing — we do have a 40-seat minimum for the team plan.", "Okay, and where does that land relative to what we're paying today?"],
                howToImprove: "Ask \"what are you budgeting for this today?\" before quoting the minimum, so the number lands in context.",
              },
            ],
          },
          {
            label: "Security objection",
            score: 95,
            questions: [
              {
                text: "Did the rep address the security question with evidence?",
                breakdownType: "good",
                value: "Yes",
                why: "The rep offered to loop in a technical deep-dive with the security team directly rather than answering from memory.",
                quotes: ["Let's get a technical deep-dive on the calendar with your security team."],
                howToImprove: "Consider sending the SOC 2 report ahead of the deep-dive so security has a head start.",
              },
            ],
          },
        ],
      },
      {
        label: "Next steps",
        metricScore: 95,
        metricSummary: "Booked a clear technical deep-dive with a named date.",
        repAvgScore: 88,
        teamAvgScore: 82,
        subMetrics: [
          {
            label: "Clear commitment",
            score: 95,
            questions: [
              {
                text: "Did the call end with a specific, dated next step?",
                breakdownType: "good",
                value: "Yes",
                why: "Both sides confirmed a concrete next meeting and named an additional stakeholder to include.",
                quotes: ["Works for me — I'll loop in procurement too."],
                howToImprove: "Send the calendar invite within the hour while the commitment is fresh.",
              },
            ],
          },
        ],
      },
    ],
    scoreCardId: "sc_discovery",
    review: {
      positiveFeedback:
        "Great use of silence after asking about current pain — let Wei fully explain before responding. Multi-threaded into procurement naturally.",
      thingsToImprove:
        "The pricing objection around the 40-seat minimum was answered quickly — worth slowing down and asking what budget range they had in mind first.",
    },
    speakers: [
      { speakerId: "speaker-0", name: "You", role: "Rep" },
      { speakerId: "speaker-1", name: "Wei Zhang", role: "Prospect" },
    ],
    transcript: [
      { speakerId: "speaker-0", atSec: 4, text: "Thanks for making time, Wei — I'd love to hear how outbound works today on your team." },
      { speakerId: "speaker-1", atSec: 18, text: "Sure. Right now our SDRs spend a lot of time just finding the right contact and verifying emails before they can even start a sequence." },
      { speakerId: "speaker-0", atSec: 34, text: "How much time would you say that eats up per rep, per week?" },
      { speakerId: "speaker-1", atSec: 41, text: "Honestly, probably a third of their week. It's a real bottleneck." },
      { speakerId: "speaker-0", atSec: 612, text: "On pricing — we do have a 40-seat minimum for the team plan." },
      { speakerId: "speaker-1", atSec: 620, text: "Okay, and where does that land relative to what we're paying today?" },
      { speakerId: "speaker-0", atSec: 1830, text: "Let's get a technical deep-dive on the calendar with your security team." },
      { speakerId: "speaker-1", atSec: 1840, text: "Works for me — I'll loop in procurement too." },
    ],
    participants: [
      { name: "You", isOwner: true, attended: true, inCrm: true },
      { name: "Wei Zhang", email: "wei.zhang@criteo.com", attended: true, inCrm: true },
      { name: "Marta Molina", email: "marta.molina@criteo.com", attended: false },
    ],
    keyFields: [
      { label: "Budget", description: "Stated or implied budget range", value: "$50K–$100K annually" },
      { label: "Decision timeline", value: "End of Q3" },
      { label: "Competitors mentioned", value: "Apollo, Outreach" },
      { label: "Team size", value: "12 SDRs" },
    ],
    prospectPosition: "Head of Sales Development",
    dealId: "deal_1",
    salesRepId: "rep_1",
  },
  {
    id: "r_2",
    title: "Demo — Softonic",
    prospectName: "Marcus Riley",
    company: "Softonic",
    date: "2026-06-15T15:00:00Z",
    durationMin: 41,
    score: 76,
    talkRatio: 58,
    sentiment: "neutral",
    highlights: ["Good product walkthrough", "Talk ratio a bit high"],
    nextSteps: ["Send ROI breakdown", "Confirm Tuesday follow-up"],
    videoSource: "teams",
    mediaKind: "video",
    summarized: true,
    analyzed: true,
    scoreCardId: "sc_discovery",
    overview:
      "Product walkthrough for Marcus's revenue ops team. Good coverage of the enrichment and sequencing features; the rep talked more than ideal.",
    scoreBreakdown: [
      {
        label: "Discovery",
        metricScore: 64,
        metricSummary: "Jumped into the demo before establishing what Marcus actually needed.",
        repAvgScore: 84,
        teamAvgScore: 79,
        subMetrics: [
          {
            label: "Open-ended questions",
            score: 58,
            questions: [
              {
                text: "Did the rep ask open-ended discovery questions?",
                breakdownType: "medium",
                value: "Partial",
                why: "One broad question early on, but the rest of the call was rep-led narration of features.",
                quotes: ["So this is the enrichment view — every contact gets 30+ data points automatically."],
                howToImprove: "Open with 10 minutes of discovery before showing a single screen.",
              },
            ],
          },
          {
            label: "Pain quantification",
            score: 70,
            questions: [
              {
                text: "Did the rep quantify the cost of the prospect's pain?",
                breakdownType: "bad",
                value: "No",
                why: "Marcus raised cost directly and the rep deferred it to a document instead of quantifying it live.",
                quotes: ["Nice, and how does that compare cost-wise to what we're doing manually today?"],
                howToImprove: "Ask what the manual process costs them per month before promising an ROI doc.",
              },
            ],
          },
        ],
      },
      {
        label: "Objection handling",
        metricScore: 72,
        metricSummary: "Cost question was acknowledged but deflected to follow-up material.",
        repAvgScore: 77,
        teamAvgScore: 74,
        subMetrics: [
          {
            label: "Pricing objection",
            score: 75,
            questions: [
              {
                text: "Did the rep uncover the prospect's budget before defending price?",
                breakdownType: "good",
                value: "Yes",
                why: "The rep asked what Softonic currently spends on manual research before quoting anything.",
                quotes: ["I'll send over an ROI breakdown by end of day."],
                howToImprove: "Good — bring the same number back verbally on the follow-up call.",
              },
            ],
          },
          {
            label: "Security objection",
            score: 68,
            questions: [
              {
                text: "Did the rep address the security question with evidence?",
                breakdownType: "medium",
                value: "Partial",
                why: "Security came up briefly and was answered from memory rather than with documentation.",
                quotes: [],
                howToImprove: "Offer the SOC 2 report rather than describing the controls verbally.",
              },
            ],
          },
        ],
      },
      {
        label: "Next steps",
        metricScore: 88,
        metricSummary: "Clear regroup agreed, though without a specific time.",
        repAvgScore: 88,
        teamAvgScore: 82,
        subMetrics: [
          {
            label: "Clear commitment",
            score: 88,
            questions: [
              {
                text: "Did the call end with a specific, dated next step?",
                breakdownType: "good",
                value: "Yes",
                why: "Both sides agreed to regroup on Tuesday with the ROI breakdown in hand.",
                quotes: ["Perfect, let's regroup Tuesday."],
                howToImprove: "Pin an exact time, not just a day, before the call ends.",
              },
            ],
          },
        ],
      },
    ],
    review: {
      positiveFeedback:
        "Thorough, confident product walkthrough — Marcus never had to ask how a feature worked twice.",
      thingsToImprove:
        "Talk ratio hit 58%. The demo started before any discovery, so the features shown weren't tied to a stated problem.",
    },
    speakers: [
      { speakerId: "speaker-0", name: "You", role: "Rep" },
      { speakerId: "speaker-1", name: "Marcus Riley", role: "Prospect" },
    ],
    transcript: [
      { speakerId: "speaker-0", atSec: 10, text: "So this is the enrichment view — every contact gets 30+ data points automatically." },
      { speakerId: "speaker-1", atSec: 95, text: "Nice, and how does that compare cost-wise to what we're doing manually today?" },
      { speakerId: "speaker-0", atSec: 2280, text: "I'll send over an ROI breakdown by end of day." },
      { speakerId: "speaker-1", atSec: 2290, text: "Perfect, let's regroup Tuesday." },
    ],
    participants: [
      { name: "You", isOwner: true, attended: true },
      { name: "Marcus Riley", email: "marcus.riley@softonic.com", attended: true, inCrm: true },
    ],
    keyFields: [
      { label: "Budget", value: "Not yet discussed" },
      { label: "Decision timeline", value: "Q3, pending internal review" },
    ],
    prospectPosition: "Head of Revenue Operations",
    dealId: "deal_2",
    salesRepId: "rep_1",
  },
  {
    id: "r_3",
    title: "Intro — Edicom",
    prospectName: "Diego Fernández",
    company: "Edicom",
    date: "2026-06-14T11:00:00Z",
    durationMin: 22,
    score: 61,
    talkRatio: 67,
    sentiment: "negative",
    highlights: ["Skeptical on ROI", "Missed budget qualification"],
    nextSteps: ["Build ROI case study", "Re-engage in 30 days"],
    videoSource: "linkedin",
    mediaKind: "video",
    summarized: false,
    analyzed: false,
    prospectPosition: "Sales Director",
    dealId: "deal_6",
    salesRepId: "rep_2",
  },
  {
    id: "r_4",
    title: "Check-in — Delta Robotics",
    prospectName: "Hugo Alvarez",
    company: "Delta Robotics",
    date: "2026-06-17T13:00:00Z",
    durationMin: 14,
    score: 69,
    talkRatio: 51,
    sentiment: "neutral",
    highlights: ["Quick pricing check-in", "Confirmed decision timeline"],
    nextSteps: ["Send updated proposal", "Follow up after board review"],
    // A regular phone call has no video track — audio-only.
    videoSource: "phone",
    mediaKind: "audio",
    summarized: true,
    analyzed: true,
    overview:
      "Short check-in call to confirm Delta Robotics' board-review timeline and re-send the updated proposal at the new seat count.",
    scoreBreakdown: [
      {
        label: "Next steps",
        metricScore: 90,
        metricSummary: "Confirmed a firm date for the board decision and what's needed before then.",
        repAvgScore: 88,
        teamAvgScore: 82,
        subMetrics: [
          {
            label: "Clear commitment",
            score: 90,
            questions: [
              {
                text: "Did the call end with a specific, dated next step?",
                breakdownType: "good",
                value: "Yes",
                why: "Hugo named the board meeting date and what he needs from the rep before then.",
                quotes: ["We review it with the board next Thursday, so if I could get the updated numbers by Wednesday that'd help."],
                howToImprove: "Confirm back the exact date verbally to lock it into the rep's own calendar on the call.",
              },
            ],
          },
        ],
      },
      {
        label: "Objection handling",
        metricScore: 72,
        metricSummary: "Pricing came up briefly; handled but not fully explored.",
        repAvgScore: 77,
        teamAvgScore: 74,
        subMetrics: [
          {
            label: "Pricing objection",
            score: 72,
            questions: [
              {
                text: "Did the rep uncover the reason behind the pricing concern?",
                breakdownType: "medium",
                value: "Partial",
                why: "The rep acknowledged the concern and offered a revised quote, but didn't ask what changed since the original proposal.",
                quotes: ["Let me get you an updated number at the new seat count."],
                howToImprove: "Ask what's driving the reconsideration before re-quoting — it may be seat count, budget cycle, or a competing option.",
              },
            ],
          },
        ],
      },
    ],
    review: {
      positiveFeedback: "Efficient, respectful of Hugo's time — got the date and the ask in under 15 minutes.",
      thingsToImprove: "Didn't probe why the seat count changed since the original proposal before agreeing to re-quote.",
    },
    speakers: [
      { speakerId: "speaker-0", name: "You", role: "Rep" },
      { speakerId: "speaker-1", name: "Hugo Alvarez", role: "Prospect" },
    ],
    transcript: [
      { speakerId: "speaker-0", atSec: 6, text: "Hey Hugo, quick one today — wanted to check in on timing." },
      { speakerId: "speaker-1", atSec: 20, text: "We review it with the board next Thursday, so if I could get the updated numbers by Wednesday that'd help." },
      { speakerId: "speaker-0", atSec: 240, text: "Let me get you an updated number at the new seat count." },
      { speakerId: "speaker-1", atSec: 250, text: "Appreciate it — that should cover what they'll ask." },
    ],
    participants: [
      { name: "You", isOwner: true, attended: true },
      { name: "Hugo Alvarez", email: "hugo.alvarez@deltarobotics.com", attended: true, inCrm: true },
    ],
    keyFields: [
      { label: "Decision timeline", value: "Board review next Thursday" },
      { label: "Seat count", value: "Increased from original proposal" },
    ],
    prospectPosition: "VP Operations",
    dealId: "deal_5",
    salesRepId: "rep_2",
    scoreCardId: "sc_checkin",
  },
  {
    id: "r_5",
    title: "Discovery — Nexi",
    prospectName: "Aisha Khan",
    company: "Clarity AI",
    date: "2026-06-12T10:30:00Z",
    durationMin: 27,
    score: 58,
    talkRatio: 71,
    sentiment: "negative",
    highlights: ["Rep dominated the conversation", "No budget or timeline established"],
    nextSteps: ["Send a shorter, problem-led follow-up", "Re-qualify before booking more time"],
    videoSource: "zoom",
    mediaKind: "video",
    summarized: true,
    analyzed: true,
    scoreCardId: "sc_discovery",
    overview:
      "Intro-to-discovery call with Aisha. The rep pitched heavily and never established the underlying problem, so the call ended without a committed next step.",
    scoreBreakdown: [
      {
        label: "Discovery",
        metricScore: 52,
        metricSummary: "Almost no discovery — the call was a pitch from minute two.",
        repAvgScore: 84,
        teamAvgScore: 79,
        subMetrics: [
          {
            label: "Open-ended questions",
            score: 48,
            questions: [
              {
                text: "Did the rep ask open-ended discovery questions?",
                breakdownType: "bad",
                value: "No",
                why: "Every question asked was a closed yes/no confirmation of a feature's value.",
                quotes: ["That'd be useful for your team, right?"],
                howToImprove: "Replace \u201cwouldn't that be useful?\u201d with \u201chow do you handle that today?\u201d",
              },
            ],
          },
          {
            label: "Pain quantification",
            score: 55,
            questions: [
              {
                text: "Did the rep quantify the cost of the prospect's pain?",
                breakdownType: "bad",
                value: "No",
                why: "No cost, time, or headcount figure was established at any point in the call.",
                quotes: [],
                howToImprove: "Anchor on a number early — hours per rep per week is the easiest one to get.",
              },
            ],
          },
        ],
      },
      {
        label: "Objection handling",
        metricScore: 60,
        metricSummary: "The one objection raised was talked over rather than explored.",
        repAvgScore: 77,
        teamAvgScore: 74,
        subMetrics: [
          {
            label: "Pricing objection",
            score: 55,
            questions: [
              {
                text: "Did the rep uncover the prospect's budget before defending price?",
                breakdownType: "bad",
                value: "No",
                why: "Aisha flagged price as a concern and the rep immediately justified the number instead of asking what she'd budgeted.",
                quotes: ["It's priced that way because of the enrichment volume included."],
                howToImprove: "Pause on a price objection and ask what range they had in mind first.",
              },
            ],
          },
          {
            label: "Security objection",
            score: 0,
            isNa: true,
            questions: [
              {
                text: "Did the rep address the security question with evidence?",
                breakdownType: "good",
                value: "N/A",
                isNa: true,
                why: "Security never came up on this call.",
                quotes: [],
                howToImprove: "No action needed — the topic wasn't raised.",
              },
            ],
          },
        ],
      },
      {
        label: "Next steps",
        metricScore: 49,
        metricSummary: "Call ended on \u201cI'll send something over\u201d with nothing booked.",
        repAvgScore: 88,
        teamAvgScore: 82,
        subMetrics: [
          {
            label: "Clear commitment",
            score: 49,
            questions: [
              {
                text: "Did the call end with a specific, dated next step?",
                breakdownType: "bad",
                value: "No",
                why: "No follow-up meeting was proposed and no date was named by either side.",
                quotes: ["I'll send some material over and we can take it from there."],
                howToImprove: "Never end a discovery call without a calendar invite sent live.",
              },
            ],
          },
        ],
      },
    ],
    review: {
      positiveFeedback:
        "Strong product knowledge — every feature question was answered accurately and quickly.",
      thingsToImprove:
        "Talk ratio of 71% is the core issue. Without discovery there was no problem to anchor the pitch to, which is why the call ended without a commitment.",
    },
    speakers: [
      { speakerId: "speaker-0", name: "You", role: "Rep" },
      { speakerId: "speaker-1", name: "Aisha Khan", role: "Prospect" },
    ],
    transcript: [
      { speakerId: "speaker-0", atSec: 12, text: "Let me walk you through what we've built — I think you'll see the fit straight away." },
      { speakerId: "speaker-1", atSec: 140, text: "Sure. Though I should say we're early in figuring out what we even need." },
      { speakerId: "speaker-0", atSec: 620, text: "That'd be useful for your team, right?" },
      { speakerId: "speaker-1", atSec: 900, text: "Possibly. What does something like this cost?" },
      { speakerId: "speaker-0", atSec: 915, text: "It's priced that way because of the enrichment volume included." },
      { speakerId: "speaker-0", atSec: 1580, text: "I'll send some material over and we can take it from there." },
    ],
    participants: [
      { name: "You", isOwner: true, attended: true },
      { name: "Aisha Khan", email: "aisha.khan@clarity.ai", attended: true, inCrm: true },
    ],
    keyFields: [
      { label: "Budget", value: "Not established" },
      { label: "Decision timeline", value: "Not established" },
    ],
    prospectPosition: "Chief Revenue Officer",
    dealId: "deal_3",
    salesRepId: "rep_2",
  },
]

// The rubrics calls can be scored against — Call Analytics' "Score Card"
// selector lets the user pick one when the filtered set of analyzed calls
// spans more than one, since aggregating across different rubrics wouldn't
// mean anything.
export const coachScoreCards: { id: string; name: string }[] = [
  { id: "sc_discovery", name: "Discovery call" },
  { id: "sc_checkin", name: "Check-in call" },
]

export const integrations: Integration[] = [
  {
    id: "in_1",
    name: "HubSpot",
    description: "Sync prospects, activities, and deals two-way.",
    connected: true,
    category: "crm",
  },
  {
    id: "in_2",
    name: "Salesforce",
    description: "Push enriched contacts and log outreach.",
    connected: false,
    category: "crm",
  },
  {
    id: "in_3",
    name: "Gmail",
    description: "Send and track emails from your inbox.",
    connected: true,
    category: "email",
  },
  {
    id: "in_4",
    name: "Google Calendar",
    description: "Book meetings and sync availability.",
    connected: true,
    category: "calendar",
  },
  {
    id: "in_5",
    name: "LinkedIn",
    description: "Source prospects and send messages.",
    connected: true,
    category: "social",
  },
  {
    id: "in_6",
    name: "SmartLead",
    description: "Run high-volume email sequences.",
    connected: false,
    category: "outreach",
  },
]

export const dashboardStats: DashboardStat[] = [
  {
    label: "Prospects added",
    value: "248",
    delta: 12.5,
    hint: "vs. last 30 days",
  },
  { label: "Reply rate", value: "18.4%", delta: 3.2, hint: "across campaigns" },
  { label: "Meetings booked", value: "23", delta: 8.0, hint: "this month" },
  {
    label: "Pipeline influenced",
    value: "$412K",
    delta: -2.1,
    hint: "open opportunities",
  },
]

export const recentActivity: ActivityItem[] = [
  {
    id: "a_1",
    type: "reply",
    prospectName: "Sarah Chen",
    detail: "replied to “Scaling outbound at Fever”",
    timestamp: "2026-06-16T14:20:00Z",
  },
  {
    id: "a_2",
    type: "meeting",
    prospectName: "Marcus Riley",
    detail: "booked a meeting for Tuesday 2pm",
    timestamp: "2026-06-15T18:05:00Z",
  },
  {
    id: "a_3",
    type: "reply",
    prospectName: "Tom Becker",
    detail: "requested a demo link on LinkedIn",
    timestamp: "2026-06-16T20:00:00Z",
  },
  {
    id: "a_4",
    type: "enriched",
    prospectName: "Grace Liu",
    detail: "enriched with 30 data points",
    timestamp: "2026-06-16T17:00:00Z",
  },
  {
    id: "a_5",
    type: "added",
    prospectName: "James O'Connor",
    detail: "added to “Q3 Enterprise ICP”",
    timestamp: "2026-06-17T07:30:00Z",
  },
]

// Live references kept in sync by the data store (src/lib/store.ts) so these
// accessors always return the current (possibly user-edited) collections.
let liveProspects: Prospect[] = prospects
let liveLists: ProspectList[] = prospectLists
let liveCampaigns: Campaign[] = campaigns

export function setLiveProspects(next: Prospect[]): void {
  liveProspects = next
}
export function setLiveLists(next: ProspectList[]): void {
  liveLists = next
}
export function setLiveCampaigns(next: Campaign[]): void {
  liveCampaigns = next
}

// Helpers
export function getProspect(id: string): Prospect | undefined {
  return liveProspects.find((p) => p.id === id)
}

export function getList(id: string): ProspectList | undefined {
  return liveLists.find((l) => l.id === id)
}

export function getCampaign(id: string): Campaign | undefined {
  return liveCampaigns.find((c) => c.id === id)
}

export function getConversationProspect(conv: Conversation): Prospect | undefined {
  return getProspect(conv.prospectId)
}

export const STATUS_LABELS: Record<Prospect["status"], string> = {
  new: "New",
  contacted: "Contacted",
  replied: "Replied",
  meeting: "Meeting",
  customer: "Customer",
  not_interested: "Not interested",
}
